-- CREATE TABLE regel (
--     id                  NUMBER(19) GENERATED ALWAYS AS IDENTITY,
--     type                VARCHAR2(20 CHAR) NOT NULL,
--     referanse           VARCHAR2(50 CHAR) NOT NULL,
--     forretning_versjon  VARCHAR2(20 CHAR) NOT NULL,
--     teknisk_versjon     VARCHAR2(20 CHAR) NOT NULL,
--     vilkaar_resultat_id NUMBER(19),
--     CONSTRAINT pk_regel PRIMARY KEY (id)
-- );
-- 
-- CREATE TABLE regel_type (
--     kode        VARCHAR2(20 CHAR) NOT NULL,
--     navn        VARCHAR2(50 CHAR) NOT NULL,
--     beskrivelse VARCHAR2(2000 CHAR),
--     CONSTRAINT pk_regel_type PRIMARY KEY (kode)
-- );
-- 
-- ALTER TABLE regel ADD CONSTRAINT fk_regel_type FOREIGN KEY (type) REFERENCES regel_type;
-- 
-- INSERT INTO regel_type (kode, navn) VALUES ('AVKLARE_FAKTA', 'Avklare fakta rettsregel');
-- INSERT INTO regel_type (kode, navn) VALUES ('BEREGNING', 'Beregning rettsregel');
-- INSERT INTO regel_type (kode, navn) VALUES ('FORRETNING', 'Forretning rettsregel');
-- INSERT INTO regel_type (kode, navn) VALUES ('VILKAAR', 'Vilkår rettsregel');