# Applikasjonens systembruker
systembruker.username=srvmelosys
systembruker.password=HEMMELIG! #IKKE sjekk inn

# Internal single sign on
isso-host.url=https://isso-t.adeo.no/isso/oauth2
isso-issuer.url=https://isso-t.adeo.no:443/isso/oauth2
isso-rp-user.username=OIDC

# LDAP-integrasjon
ldap.url=ldap://ldapgw.test.local
ldap.username=srvSSOLinux
ldap.domain=TEST.LOCAL
ldap.password=HEMMELIG! #IKKE sjekk inn
ldap.user.basedn=ou\=NAV,ou\=BusinessUnits,dc\=test,dc\=local

# STS web service
securityTokenService.url=https://sts-t4.test.local/SecurityTokenServiceProvider/

# AAREG
Arbeidsforhold_v3.url=https://modapp-t4.adeo.no/aareg-core/ArbeidsforholdService/v3

# EREG, Enhetsregisteret
Organisasjon_v4.url=https://modapp-t4.adeo.no/ereg/ws/OrganisasjonService/v4

# GSAK web service
BehandleSak_v1.url=https://wasapp-t4.adeo.no/nav-gsak-ws/BehandleSakV1
Sak_v1.url=https://wasapp-t4.adeo.no/nav-gsak-ws/SakV1

# Inntektskomponenten
Inntekt_v3.url=https://app-t4.adeo.no/inntektskomponenten-ws/inntekt/v3/Inntekt

# JOARK web service
Journal_v2.url=https://wasapp-t4.adeo.no/joark/Journal/v2
InngaaendeJournal_v1.url=https://wasapp-t4.adeo.no/joark/InngaaendeJournal/v1
BehandleInngaaendeJournal_v1.url=https://wasapp-t4.adeo.no/joark/BehandleInngaaendeJournal/v1

# TPS web service
Aktoer_v2.url=https://app-t4.adeo.no/aktoerid/AktoerService/v2
Person_v2.url=https://wasapp-t4.adeo.no/tpsws/Person_v2
Person_v3.url=https://wasapp-t4.adeo.no/tpsws/ws/Person/v3

# Kodeverk service
koveverk_v2.url=https://modapp-t4.adeo.no/kodeverk/ws/Kodeverk/v2
