# Applikasjonens systembruker
systembruker.username=srvEESSI2
systembruker.password=HEMMELIG

#AAREG
Arbeidsforhold_v3.url=https://modapp-t4.adeo.no/aareg-core/ArbeidsforholdService/v3

#GSAK web service
BehandleSak_v1.url=https://wasapp-t11.adeo.no/nav-gsak-ws/BehandleSakV1
Sak_v1.url=https://wasapp-t11.adeo.no/nav-gsak-ws/SakV1

#JOARK web service
Journal_v2.url=https://wasapp-t11.adeo.no/joark/Journal/v2
InngaaendeJournal_v1.url=https://wasapp-t11.adeo.no/joark/InngaaendeJournal/v1
BehandleInngaaendeJournal_v1.url=https://wasapp-t11.adeo.no/joark/BehandleInngaaendeJournal/v1

# TPS web service
Aktoer_v2.url=https://app-t11.adeo.no/aktoerid/AktoerService/v2
Person_v2.url=https://wasapp-t11.adeo.no/tpsws/Person_v2

# Internal single sign on
isso-host.url=https://isso-t.adeo.no/isso/oauth2
isso-jwks.url=https://isso-t.adeo.no/isso/oauth2/connect/jwk_uri
isso-issuer.url=https://isso-t.adeo.no:443/isso/oauth2
isso-rp-user.username=OIDC
#isso-rp-user.password=********

# STS web service
securityTokenService.url=https://sts-t11.test.local/SecurityTokenServiceProvider/

# LDAP-integrasjon
ldap.url=ldap://ldapgw.test.local
ldap.username=srvEESSI2
ldap.domain=TEST.LOCAL
#HEMMELIG! #IKKE sjekk inn
ldap.password=5lz9x69d
ldap.user.basedn=ou\=NAV,ou\=BusinessUnits,dc\=test,dc\=local