
# Hvor mange år tilbake i tid vi henter arbeidsforhold for
melosys.service.fagsak.arbeidsforholdhistorikk.antallMåneder=6
# Hvor mange måneder tilbake i tid vi henter inntekt for
melosys.service.fagsak.inntektshistorikk.antallMåneder=6
# Hvor mange år tilbake i tid vi henter medlemskap for
melosys.service.fagsak.medlemskaphistorikk.antallÅr=5

# Hvor ofte aktørId-cache sjekkes for elementer som skal fjernes
melosys.service.aktørid.millisMellomVåkneOpp=3600000
# Hvor lenge aktørId skal leve i cache
melosys.service.aktørid.millisLevetidICache=28800000
# Hvor mange elementer regner vi med at cachen kommer til å holde (bør være en potens av 2)
melosys.service.aktørid.initiellKapasitetICache=1024
