
# Hvor mange år tilbake i tid vi henter arbeidsforhold for
melosys.service.fagsak.arbeidsforholdhistorikk.antallMåneder=6
# Hvor mange måneder tilbake i tid vi henter inntekt for
melosys.service.fagsak.inntektshistorikk.antallMåneder=6
# Hvor mange år tilbake i tid vi henter medlemskap for
melosys.service.fagsak.medlemskaphistorikk.antallÅr=5
