
# Hvor mange måneder tilbake i tid vi henter arbeidsforhold for
melosys.service.fagsak.arbeidsforholdhistorikk.antallMåneder=12
# Hvor mange måneder tilbake i tid vi henter inntekt for
melosys.service.fagsak.inntektshistorikk.antallMåneder=12
# Regelmodul url
melosys.service.regelmodul.url=http://localhost:8081/lovvalg/fastsettLovvalg