
# Hvor mange år tilbake i tid vi henter arbeidsforhold for
melosys.service.fagsak.arbeidsforholdhistorikk.antallÅr=5
# Hvor mange måneder tilbake i tid vi henter inntekt for
melosys.service.fagsak.inntektshistorikk.antallMåneder=12