alter table AKTOER modify id generated by default as identity;

INSERT INTO AKTOER (ID, FAGSAK_ID, AKTOER_ID, EKSTERN_ID, ROLLE) VALUES(1, 3, 'FJERNET', 'FJERNET', 'BRUKER');

alter table AKTOER modify id generated always as identity (START WITH LIMIT VALUE);