alter table FAGSAK modify id generated by default as identity;

INSERT INTO FAGSAK (ID, SAKSNUMMER, FAGSAK_TYPE, VERSJON, STATUS, REGISTRERT_DATO)
VALUES(3, 123, 'A1', 0, 'OPPR', TIMESTAMP '2017-10-19 12:31:36.000000');

alter table FAGSAK modify id generated always as identity (START WITH LIMIT VALUE);