alter table BEHANDLING modify id generated by default as identity;

INSERT INTO BEHANDLING (ID, GSAK_ID, FAGSAK_ID, STATUS, STEG, BEH_TYPE, REGISTRERT_DATO)
VALUES(3, 123, 3, 'OPPR', NULL, 'SØKNAD', TIMESTAMP '2017-10-19 14:35:54.000000');

alter table BEHANDLING modify id generated always as identity (START WITH LIMIT VALUE);

