apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: melosys
  namespace: @@NAMESPACE@@
  labels:
    team: teammelosys
spec:
  image: docker.adeo.no:5000/melosys/melosys:@@IMAGE_VERSION@@
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  liveness:
    path: internal/isAlive
    initialDelay: 240
    timeout: 10
  readiness:
    path: internal/health
    initialDelay: 120
    timeout: 10
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 768Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: internal/prometheus
  ingresses:
  - "https://@@URL@@"