apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: melosys
  namespace: @@NAMESPACE@@
  labels:
    team: teammelosys
spec:
  image: repo.adeo.no:5443/melosys/melosys:@@IMAGE_VERSION@@
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  liveness:
    path: internal/health
    initialDelay: 1200
    timeout: 10
  readiness:
    path: internal/health
    initialDelay: 600
    timeout: 10
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
  - "https://@@URL@@"