package no.nav.melosys.service.behandling;

import java.util.Set;

import no.nav.melosys.domain.kodeverk.behandlinger.Behandlingstema;
import no.nav.melosys.domain.kodeverk.behandlinger.Behandlingstyper;

import static no.nav.melosys.domain.kodeverk.behandlinger.Behandlingstema.*;
import static no.nav.melosys.domain.kodeverk.behandlinger.Behandlingstyper.*;

public class LovligeBehandlingsKombinasjoner {
    // EU_EØS
    private static final Set<Behandlingstema> EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_1 = Set.of(UTSENDT_ARBEIDSTAKER, UTSENDT_SELVSTENDIG, ARBEID_TJENESTEPERSON_ELLER_FLY, ARBEID_FLERE_LAND, ARBEID_KUN_NORGE, IKKE_YRKESAKTIV, PENSJONIST);
    private static final Set<Behandlingstema> EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_2 = Set.of(FORESPØRSEL_TRYGDEMYNDIGHET, TRYGDETID);
    private static final Set<Behandlingstema> EU_EOS_UNNTAK_BEHANDLINGSTEMA_BRUKER = Set.of(FORESPØRSEL_TRYGDEMYNDIGHET);
    private static final Set<Behandlingstema> EU_EOS_TRYGDEAVGIFT_BEHANDLINGSTEMA_BRUKER = Set.of(YRKESAKTIV, PENSJONIST);
    private static final Set<Behandlingstyper> EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_1 = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    private static final Set<Behandlingstyper> EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_2 = Set.of(HENVENDELSE);
    private static final Set<Behandlingstyper> EU_EOS_UNNTAK_BEHANDLINGSTYPE_BRUKER = Set.of(HENVENDELSE);
    private static final Set<Behandlingstyper> EU_EOS_TRYGDEAVGIFT_BEHANDLINGSTYPE_BRUKER = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    public static final BehandlingsKombinasjon EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGS_KOMBINASJON_1 = new BehandlingsKombinasjon(EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_1, EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_1);
    public static final BehandlingsKombinasjon EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGS_KOMBINASJON_2 = new BehandlingsKombinasjon(EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_2, EU_EOS_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_2);
    public static final BehandlingsKombinasjon EU_EOS_UNNTAK_BEHANDLINGS_KOMBINASJON = new BehandlingsKombinasjon(EU_EOS_UNNTAK_BEHANDLINGSTEMA_BRUKER, EU_EOS_UNNTAK_BEHANDLINGSTYPE_BRUKER);
    public static final BehandlingsKombinasjon EU_EOS_TRYGDEAVGIFT_BEHANDLINGS_KOMBINASJON = new BehandlingsKombinasjon(EU_EOS_TRYGDEAVGIFT_BEHANDLINGSTEMA_BRUKER, EU_EOS_TRYGDEAVGIFT_BEHANDLINGSTYPE_BRUKER);

    // FOLKETRYGDLOVEN
    private static final Set<Behandlingstema> FOLKETRYGDLOVEN_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER = Set.of(IKKE_YRKESAKTIV, YRKESAKTIV, PENSJONIST, UNNTAK_MEDLEMSKAP);
    private static final Set<Behandlingstema> FOLKETRYGDLOVEN_TRYGDEAVGIFT_BEHANDLINGSTEMA_BRUKER = Set.of(YRKESAKTIV, PENSJONIST);
    private static final Set<Behandlingstyper> FOLKETRYGDLOVEN_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    private static final Set<Behandlingstyper> FOLKETRYGDLOVEN_TRYGDEAVGIFT_BEHANDLINGSTYPE_BRUKER = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    public static final BehandlingsKombinasjon FOLKETRYGDLOVEN_LOVVALG_MEDLEMSKAP_BEHANDLINGS_KOMBINASJON = new BehandlingsKombinasjon(FOLKETRYGDLOVEN_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER, FOLKETRYGDLOVEN_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER);
    public static final BehandlingsKombinasjon FOLKETRYGDLOVEN_TRYGDEAVGIFT_BEHANDLINGS_KOMBINASJON = new BehandlingsKombinasjon(FOLKETRYGDLOVEN_TRYGDEAVGIFT_BEHANDLINGSTEMA_BRUKER, FOLKETRYGDLOVEN_TRYGDEAVGIFT_BEHANDLINGSTYPE_BRUKER);

    // TRYGDEAVTALE
    private static final Set<Behandlingstema> TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_1 = Set.of(IKKE_YRKESAKTIV, YRKESAKTIV, PENSJONIST);
    private static final Set<Behandlingstema> TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_2 = Set.of(FORESPØRSEL_TRYGDEMYNDIGHET);
    private static final Set<Behandlingstema> TRYGDEAVTALE_UNNTAK_BEHANDLINGSTEMA_BRUKER_1 = Set.of(ANMODNING_OM_UNNTAK_HOVEDREGEL, REGISTRERING_UNNTAK);
    private static final Set<Behandlingstema> TRYGDEAVTALE_UNNTAK_BEHANDLINGSTEMA_BRUKER_2 = Set.of(FORESPØRSEL_TRYGDEMYNDIGHET);
    private static final Set<Behandlingstema> TRYGDEAVTALE_TRYGDEAVGIFT_BEHANDLINGSTEMA_BRUKER = Set.of(YRKESAKTIV, PENSJONIST);
    private static final Set<Behandlingstyper> TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_1 = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    private static final Set<Behandlingstyper> TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_2 = Set.of(HENVENDELSE);
    private static final Set<Behandlingstyper> TRYGDEAVTALE_UNNTAK_BEHANDLINGSTYPE_BRUKER_1 = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    private static final Set<Behandlingstyper> TRYGDEAVTALE_UNNTAK_BEHANDLINGSTYPE_BRUKER_2 = Set.of(HENVENDELSE);
    private static final Set<Behandlingstyper> TRYGDEAVTALE_TRYGDEAVGIFT_BEHANDLINGSTYPE_BRUKER = Set.of(FØRSTEGANG, NY_VURDERING, KLAGE, HENVENDELSE);
    public static final BehandlingsKombinasjon TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGS_KOMBINASJON_1 = new BehandlingsKombinasjon(TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_1, TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_1);
    public static final BehandlingsKombinasjon TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGS_KOMBINASJON_2 = new BehandlingsKombinasjon(TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTEMA_BRUKER_2, TRYGDEAVTALE_LOVVALG_MEDLEMSKAP_BEHANDLINGSTYPE_BRUKER_2);
    public static final BehandlingsKombinasjon TRYGDEAVTALE_UNNTAK_BEHANDLINGS_KOMBINASJON_1 = new BehandlingsKombinasjon(TRYGDEAVTALE_UNNTAK_BEHANDLINGSTEMA_BRUKER_1, TRYGDEAVTALE_UNNTAK_BEHANDLINGSTYPE_BRUKER_1);
    public static final BehandlingsKombinasjon TRYGDEAVTALE_UNNTAK_BEHANDLINGS_KOMBINASJON_2 = new BehandlingsKombinasjon(TRYGDEAVTALE_UNNTAK_BEHANDLINGSTEMA_BRUKER_2, TRYGDEAVTALE_UNNTAK_BEHANDLINGSTYPE_BRUKER_2);
    public static final BehandlingsKombinasjon TRYGDEAVTALE_TRYGDEAVGIFT_BEHANDLINGS_KOMBINASJON = new BehandlingsKombinasjon(TRYGDEAVTALE_TRYGDEAVGIFT_BEHANDLINGSTEMA_BRUKER, TRYGDEAVTALE_TRYGDEAVGIFT_BEHANDLINGSTYPE_BRUKER);

    // VIRKSOMHET - har alle behandlingstema på alle sakstema og type
    public static final Set<Behandlingstyper> BEHANDLINGSTYPER_FOR_VIRKSOMHET = Set.of(HENVENDELSE);
}
