spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.53.103.77/MELOSYS_Q2
    username: MELOSYS_Q2
    password: ${melosysDB.password}
  flyway:
    enabled: false
  # Validerer Hibernate mapping
  jpa:
    hibernate:
      ddl-auto: validate

# Systembruker konfigurasjon
systemuser:
  username: srvmelosys
  password: ${systemuser.password}

# Kubernetes Azure konfigurasjon
kubernetes:
  azure:
    kubelogin:
      path: ${KUBELOGIN_PATH:/home/linuxbrew/.linuxbrew/bin}
    kubectl:
      path: ${KUBECTL_PATH:/usr/local/bin}

# Token-validering
no:
  nav:
    security:
      jwt:
        issuer:
          aad:
            discoveryurl: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
            accepted-audience: ${AZURE_APP_CLIENT_ID}
    # ABAC
    abac:
      url: https://abac-melosys-q2.dev.intern.nav.no/application/asm-pdp/authorize

# Soap-klient policy
stsPolicy:
  url: classpath:stsPolicy.xml

# Eksterne service integrasjoner

# AAREG
arbeidsforhold:
  rest:
    url: https://aareg-services.dev.intern.nav.no/api/v1/arbeidstaker/arbeidsforhold

# DOKSYS
Dokumentproduksjon_v3:
  url: https://dokprod-q2.dev.intern.nav.no/dokprod/ws/dokumentproduksjon/v3

DistribuerJournalpost_v1:
  url: https://dokdistfordeling-q2.dev.intern.nav.no/rest/v1/distribuerjournalpost

# EREG, Enhetsregisteret
ereg:
  rest:
    url: https://ereg-services-q2.dev.intern.nav.no/api/v2

# GSAK web service
SakAPI_v1:
  url: https://sak-q2.dev.intern.nav.no/api/v1/saker

OppgaveAPI_v1:
  url: https://oppgave.dev.intern.nav.no/api/v1

# Inntektskomponenten
inntekt:
  rest:
    url: https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q2/rs/api/v1

# JournalpostAPI
JournalpostApi_v1:
  url: https://dokarkiv-q2.dev.intern.nav.no/rest/journalpostapi/v1

# SAF
SAF:
  url: https://saf-q2.dev.intern.nav.no

# PDL
PDL:
  url: https://pdl-api.dev.intern.nav.no/graphql

# TPS web service
Person_v3:
  url: https://wasapp-q2.adeo.no/tpsws/ws/Person/v3

# Kodeverk service
KodeverkAPI_v1:
  url: https://kodeverk-api.nav.no/api

# MEDL2
medlemskap:
  rest:
    url: https://medlemskap-medl-api.dev.intern.nav.no/api/v1/medlemskapsunntak

# MICROSOFT GRAPH
microsoft:
  graph:
    rest:
      url: https://graph.microsoft.com/v1.0

# SBEH behandlingskjede
SakOgBehandling_v1:
  url: https://modapp.adeo.no/sakogbehandling/ws/SakOgBehandling_v1

# Utbetaldata
Utbetaling_v1:
  url: https://wasapp-q2.adeo.no/nav-utbetaldata-ws/virksomhet/Utbetaling_v1

utbetaling_rest:
  url: https://sokos-utbetaldata.dev.intern.nav.no/utbetaldata/api/v2/hent-utbetalingsinformasjon/intern

# Inngangsvilkar
Inngangsvilkaar:
  url: https://melosys-inngangsvilkar.intern.dev.nav.no/api

# REST-STS
REST_STS:
  url: https://security-token-service.dev.adeo.no/rest/v1/sts

# SBEH queue
SBEH:
  queueName: QA.Q_TRASH.QUEUE
  username: srvappserver

# Melosys-applikasjoner
MelosysEessi:
  url: https://melosys-eessi.dev.intern.nav.no/api

faktureringskomponenten:
  url: https://faktureringskomponenten-q2.intern.dev.nav.no

MelosysSoknadMottak:
  url: https://melosys-soknad-mottak.dev.intern.nav.no/api

melosystrygdeavgift:
  url: https://melosys-trygdeavgift-beregning.intern.dev.nav.no/api

melosysdokgen:
  v1:
    url: https://melosys-dokgen.intern.dev.nav.no/api/v1

# Apikey til ProsessinstansAdminTjenste
Melosys-admin:
  apikey: dummy

# Kafka
kafka:
  aiven:
    eessi:
      groupId: teammelosys-eessiMelding-consumer
      topic: teammelosys.eessi.v1-q2:teammelosys.eessi.v1
    soknad-mottak:
      topic: teammelosys.soknad-mottak.v1-q2:teammelosys.soknad-mottak.v1
      groupid: teammelosys-soknad-mottak-consumer
    a1-utstedt:
      topic: teammelosys.melosys-utstedt-a1.v1-q2:teammelosys.melosys-utstedt-a1.v1
    manglende-fakturabetaling:
      topic: teammelosys.manglende-fakturabetaling.v1-q2
      groupid: teammelosys.manglende-fakturabetaling-consumer
    melosys-hendelser:
      topic: teammelosys.melosys-hendelser.v1-q2
    skattehendelser:
      groupid: teammelosys.skattehendelser-consumer

spring:
  kafka:
    properties:
      sasl:
        jaas:
          config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${systemuser.username}" password="${systemuser.password}";'
        mechanism: PLAIN
      reconnect:
        backoff:
          ms: 1000
      security:
        protocol: SASL_SSL

# Unleash
unleash:
  token: faketoken

# Disable lDAP health check for Actuator
management:
  health:
    ldap:
      enabled: false

# Client scopes for Entra (Azure AD)
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token

NAIS_CLUSTER_NAME: dev-fss
NAIS_CLUSTER_NAME_GCP: dev-gcp

APP_NAME_PDL: pdl-api
APP_NAME_OPPGAVE: oppgave
APP_NAME_SAF: saf
APP_NAME_MEDL: medlemskap-medl-api
APP_NAME_MELOSYS_EESSI: melosys-eessi
APP_NAME_ARBEIDSFORHOLD: aareg-services-nais
APP_NAME_INNTEKTSKOMPONENTEN: inntektskomponenten
APP_NAME_UTBETALING: sokos-utbetaldata
APP_NAME_FAKTURERINGSKOMPONENTEN: faktureringskomponenten-q2
APP_NAME_FELLESKODEVERK: kodeverk-api

# Logging av RestTemplate
logging:
  level:
    org.springframework.web.client.RestTemplate: INFO 