# Server
server.forward-headers-strategy=native

# Actuator og metrikker
management.endpoints.web.base-path=/internal
management.endpoints.web.exposure.include=health,prometheus
management.health.diskspace.enabled=false
management.metrics.web.server.request.autotime.enabled=true
management.metrics.enable[process.start.time]=false
management.metrics.enable[jvm.threads.peak]=false
management.metrics.enable[jvm.threads.daemon]=false
management.metrics.enable[jvm.classes.loaded]=false
management.metrics.enable[jvm.classes.unloaded]=false

# Caching
spring.cache.type=caffeine
spring.cache.cache-names=aktoerID,folkeregisterIdent
spring.cache.caffeine.spec.maximumSize=2048
spring.cache.caffeine.spec.expireAfterWrite=480m

# Datasource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${melosysDB.url}
spring.datasource.username=${melosysDB.username}
spring.datasource.password=${melosysDB.password}
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.open-in-view=false

# Task execution
spring.task.execution.pool.core-size=1
spring.task.execution.pool.max-size=4

# Jackson
spring.jackson.default-property-inclusion=ALWAYS
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.mapper.default-view-inclusion=true

# Kafka
spring.kafka.bootstrap-servers=${kafka.brokers}

# ABAC
no.nav.abac.systemuser.username=${systemuser.username}
no.nav.abac.systemuser.password=${systemuser.password}

#Flyway
spring.flyway.out-of-order=true
