# OpenIDConnect (OpenAM)
security.oidc.issoHost=${OPENIDCONNECT_URL}/oauth2
security.oidc.discoveryUrl=${OPENIDCONNECT_URL}/oauth2/.well-known/openid-configuration
security.oidc.username=${NAIS_APP_NAME}-${ENV_NAME}
security.oidc.password=${OPENIDCONNECTAGENT_PASSWORD}

# LDAP
ldap.url=${LDAP_URL}
ldap.username=${LDAP_USERNAME}
ldap.domain=${LDAP_DOMAIN}
ldap.password=${LDAP_PASSWORD}
ldap.user.basedn=${LDAP_USER_BASEDN}

# SecurityTokenService
securityTokenService.url=${SECURITYTOKENSERVICE_URL}
systemuser.username=${SRVMELOSYS_USERNAME}
systemuser.password=${SRVMELOSYS_PASSWORD}

# AAREG
Arbeidsforhold_v3.url=${VIRKSOMHET_ARBEIDSFORHOLD_V3_ENDPOINTURL}

# DOKSYS
Dokumentproduksjon_v3.url=${DOKUMENTPRODUKSJON_V3_ENDPOINTURL}

# EREG, Enhetsregisteret
Organisasjon_v4.url=${VIRKSOMHET_ORGANISASJON_V4_ENDPOINTURL}

# GSAK web service
SakAPI_v1.url=${SAK_SAKER_URL}
OppgaveAPI_v1.url=${OPPGAVE_OPPGAVER_URL}

# Inntektskomponenten
Inntekt_v3.url=${VIRKSOMHET_INNTEKT_V3_ENDPOINTURL}

# JOARK web service
Journal_v3.url=${JOURNAL_V3_ENDPOINTURL}
InngaaendeJournal_v1.url=${INNGAAENDEJOURNAL_V1_ENDPOINTURL}
JournalfoerInngaaende_v1.url=${JOURNALFOERINNGAAENDE_V1_URL}

# TPS web service
Aktoer_v2.url=${AKTOER_V2_ENDPOINTURL}
Person_v3.url=${VIRKSOMHET_PERSON_V3_ENDPOINTURL}

# Kodeverk service
KodeverkAPI_v1.url=${KODEVERK_REST_API_URL}

# MEDL2
Medlemskap_v2.url=${VIRKSOMHET_MEDLEMSKAP_V2_ENDPOINTURL}
BehandleMedlemskap_v2.url=${VIRKSOMHET_BEHANDLEMEDLEMSKAP_V2_ENDPOINTURL}

# SBEH behandlingskjede
SakOgBehandling_v1.url=${SAKOGBEHANDLING_ENDPOINTURL}

# Regelmodul
melosys.service.regelmodul.url=${MELOSYS_REGELMODUL_ENDPOINTURL}

#REST-STS
REST_STS.url=${SECURITY_TOKEN_SERVICE_TOKEN_URL}

# Queue manager
queueManager.hostName=${MQGATEWAY02_HOSTNAME}
queueManager.port=${MQGATEWAY02_PORT}
queueManager.name=${MQGATEWAY02_NAME}
queueManager.channel=${MELOSYS_CHANNEL_NAME}
queueManager.useSsl=false

# SBEH queue
SBEH.queueName=${SBEH_SAKSBEHANDLING_QUEUENAME}

# ABAC
no.nav.abac.url=${ABAC_PDP_ENDPOINT_URL}

# Melosys-eessi
MelosysEessi.url=http://melosys-eessi/api
MelosysEessi.apiHeader=${MELOSYS_EESSI_APIKEY_USERNAME}
MelosysEessi.apiKey=${MELOSYS_EESSI_APIKEY_PASSWORD}
MelosysEessi.forsokSendSed=${SKAL_SENDE_SED}

# Kafka
kafka.brokers=${KAFKA_BROKERS_URL}
kafka.groupid=melosys-eessiMelding-consumer

melosys.security.melosys_ad_group=${MELOSYS_AD_GROUP}
