spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@10.51.9.59:1521/MELOSYS_Q1
spring.datasource.username=MELOSYS_Q1

# Validerer Hibernate mapping
spring.jpa.hibernate.ddl-auto=validate

#Token-validering
no.nav.security.jwt.issuer.aad.discoveryurl=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
no.nav.security.jwt.issuer.aad.accepted-audience=${AZURE_APP_CLIENT_ID}

no.nav.security.jwt.client.registration.pdl.token-endpoint-url=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
no.nav.security.jwt.client.registration.pdl.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.pdl.scope=api://dev-fss.pdl.pdl-api/.default
no.nav.security.jwt.client.registration.pdl.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.pdl.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.pdl.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.oppgave.token-endpoint-url=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
no.nav.security.jwt.client.registration.oppgave.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.oppgave.scope=api://dev-fss.oppgavehandtering.oppgave-q1/.default
no.nav.security.jwt.client.registration.oppgave.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.oppgave.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.oppgave.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.saf.token-endpoint-url=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
no.nav.security.jwt.client.registration.saf.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.saf.scope=api://dev-fss.teamdokumenthandtering.saf-q1/.default
no.nav.security.jwt.client.registration.saf.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.saf.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.saf.authentication.client-auth-method=client_secret_basic


no.nav.security.jwt.client.registration.medl.token-endpoint-url=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
no.nav.security.jwt.client.registration.medl.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.medl.scope=api://dev-fss.team-rocket.medlemskap-medl-api-q1/.default
no.nav.security.jwt.client.registration.medl.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.medl.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.medl.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.melosys-eessi.token-endpoint-url=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
no.nav.security.jwt.client.registration.melosys-eessi.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.melosys-eessi.scope=api://dev-fss.teammelosys.melosys-eessi-q1/.default
no.nav.security.jwt.client.registration.melosys-eessi.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.melosys-eessi.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.melosys-eessi.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.faktureringskomponenten.token-endpoint-url=https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
no.nav.security.jwt.client.registration.faktureringskomponenten.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.faktureringskomponenten.scope=api://dev-fss.teammelosys.melosys-faktureringskomponenten-q1/.default
no.nav.security.jwt.client.registration.faktureringskomponenten.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.faktureringskomponenten.authentication.client-secret=${AZURE_APP_CLIENT_SECRET}
no.nav.security.jwt.client.registration.faktureringskomponenten.authentication.client-auth-method=client_secret_basic

# SecurityTokenService
securityTokenService.url=https://sts-q1.dev.intern.nav.no/SecurityTokenServiceProvider/
stsPolicy.url=classpath:stsPolicy.xml
systemuser.username=srvmelosys
systemuser.password=${systemuser.password}

# AAREG
Arbeidsforhold_v3.url=https://modapp-q1.adeo.no/aareg-core/ArbeidsforholdService/v3
arbeidsforhold.rest.url=https://aareg-services.dev.intern.nav.no/api/v1/arbeidstaker/arbeidsforhold

# DOKSYS
Dokumentproduksjon_v3.url=https://dokprod-q1.dev.intern.nav.no/dokprod/ws/dokumentproduksjon/v3
DistribuerJournalpost_v1.url=https://dokdistfordeling-q1.dev.intern.nav.no/rest/v1/distribuerjournalpost

# EREG, Enhetsregisteret
Organisasjon_v4.url=https://ereg-services-q1.dev.intern.nav.no/ws/OrganisasjonService/v4

# GSAK web service
SakAPI_v1.url=https://sak-q1.dev.adeo.no/api/v1/saker
OppgaveAPI_v1.url=https://oppgave-q1.dev.intern.nav.no/api/v1

# Inntektskomponenten
Inntekt_v3.url=https://modapp-q1.adeo.no/inntektskomponenten-ws/inntekt/v3/Inntekt

# JournalpostAPI
JournalpostApi_v1.url=https://dokarkiv-q1.dev.intern.nav.no/rest/journalpostapi/v1

# SAF
SAF.url=https://saf-q1.dev.intern.nav.no

# PDL - Q2
PDL.url=https://pdl-api.dev.intern.nav.no/graphql

# TPS web service
Person_v3.url=https://wasapp-q1.adeo.no/tpsws/ws/Person/v3

# Kodeverk service
KodeverkAPI_v1.url=https://kodeverk.dev.adeo.no/api

# MEDL2
medlemskap.rest.url=https://app-q1.adeo.no/medl2/api/v1/medlemskapsunntak

# SBEH behandlingskjede
SakOgBehandling_v1.url=https://modapp-q1.adeo.no/sakogbehandling/ws/SakOgBehandling_v1

# Utbetaling
Utbetaling_v1.url=https://wasapp-q1.adeo.no/nav-utbetaldata-ws/virksomhet/Utbetaling_v1

# Inngangsvilkar
Inngangsvilkaar.url=https://melosys-inngangsvilkar.dev.intern.nav.no/api

#REST-STS #https://api-gw-q1.oera.no/security-token-service
REST_STS.url=https://security-token-service.dev.adeo.no/rest/v1/sts/token

# SBEH queue
SBEH.queueName=QA.Q_TRASH.QUEUE
SBEH.username=srvappserver

# ABAC
no.nav.abac.url=https://abac-melosys-q1.dev.intern.nav.no/application/asm-pdp/authorize

# Melosys-applikasjoner
MelosysEessi.url=https://melosys-eessi.dev.intern.nav.no/api
faktureringskomponenten.url=http://faktureringskomponenten-q1.dev.intern.nav.np
MelosysSoknadMottak.url=https://melosys-soknad-mottak.dev.intern.nav.no/api
melosystrygdeavgift.url=https://melosys-trygdeavgift.dev.intern.nav.no/api
melosysdokgen.v1.url=https://melosys-dokgen.dev.intern.nav.no/api/v1
melosysavgiftoverforing.url=https://melosys-avgift-overforing.dev.intern.nav.no/api

# Apikey til ProsessinstansAdminTjenste
Melosys-admin.apikey=dummy

# Kafka
kafka.aiven.eessi.groupId=teammelosys-eessiMelding-consumer
kafka.aiven.eessi.topic=teammelosys.eessi.v1-q1:teammelosys.eessi.v1
kafka.aiven.soknad-mottak.topic=teammelosys.soknad-mottak.v1-q1:teammelosys.soknad-mottak.v1
kafka.aiven.soknad-mottak.groupid=teammelosys-soknad-mottak-consumer
kafka.aiven.a1-utstedt.topic=teammelosys.melosys-utstedt-a1.v1-q1:teammelosys.melosys-utstedt-a1.v1
kafka.fattetvedtak.topic=teammelosys.fattetvedtak.v1-q1:teammelosys.fattetvedtak.v1

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${systemuser.username}" password="${systemuser.password}";
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_SSL

# Disable lDAP health check for Actuator
management.health.ldap.enabled=false
logging.level.org.springframework.web.client.RestTemplate=DEBUG
