spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/${MELOSYS_ORACLE_DB_NAME:XEPDB1}
spring.datasource.username=melosys
spring.datasource.password=melosyspwd

systemuser.username=srvmelosys
systemuser.password=dummy

# Validerer Hibernate mapping
spring.jpa.hibernate.ddl-auto=validate

no.nav.security.jwt.issuer.aad.discovery-url=http://host.docker.internal:8082/isso/.well-known/openid-configuration
no.nav.security.jwt.issuer.aad.accepted-audience=melosys-localhost

stsPolicy.url=classpath:stsPolicy.xml

# AAREG
arbeidsforhold.rest.url=http://localhost:8083/aareg-services/api/v1/arbeidstaker/arbeidsforhold

# DOKSYS
Dokumentproduksjon_v3.url=http://localhost:8083/soap/services/dokumentproduksjon/v3
DistribuerJournalpost_v1.url=http://localhost:8083/rest/v1/distribuerjournalpost
dokumentproduksjon.uten.token=true

# EREG, Enhetsregisteret
ereg.rest.url=http://localhost:8083/ereg/v2


# GSAK web service
SakAPI_v1.url=http://localhost:8083/api/v1/saker
OppgaveAPI_v1.url=http://localhost:8083/api/v1

# Inntektskomponenten
inntekt.rest.url=http://localhost:8083/inntektskomponenten/rs/api/v1

# JournalpostAPI
JournalpostApi_v1.url=http://localhost:8083/rest/journalpostapi/v1

# SAF
SAF.url=http://localhost:8083

# PDL
PDL.url=http://localhost:8083/graphql

# Kodeverk service
KodeverkAPI_v1.url=https://kodeverk-api.nav.no/api

# MEDL2
medlemskap.rest.url=http://localhost:8083/medl2/api/v1/medlemskapsunntak

# MICROSOFT GRAPH
microsoft.graph.rest.url=http://localhost:8083/graph/v1.0

# SBEH behandlingskjede
SakOgBehandling_v1.url=http://localhost:8083/soap/services/sakOgBehandling/v1

# Utbetaldata
utbetaling_rest.url=http://localhost:8083/utbetaldata/api/v2/hent-utbetalingsinformasjon/intern

# Inngangsvilkar
Inngangsvilkaar.url=https://melosys-inngangsvilkar.intern.dev.nav.no/api

#REST-STS
REST_STS.url=http://localhost:8086/reststs

#Unleash
unleash.token=faketoken

# Queue manager
queueManager.hostName=host.docker.internal
queueManager.port=41414
queueManager.name=SOB_QM
queueManager.channel=DEV.APP.SVRCONN
queueManager.useSsl=false

# ABAC
no.nav.abac.url=http://localhost:8083/asm-pdp/authorize

# Melosys-applikasjoner
# Faktureringskomponenten
faktureringskomponenten.url=http://localhost:8084

# For lokal testing:
#MelosysEessi.url=http://localhost:8081/api
MelosysSoknadMottak.url=http://localhost:8082/api
melosystrygdeavgift.url=http://localhost:8095/api

MelosysEessi.url=http://localhost:8083/api
# Melosys Dokgen
melosysdokgen.v1.url=${MELOSYSDOKGEN_V1_URL:http://localhost:8888/api/v1}

# Apikey til ProsessinstansAdminTjenste
Melosys-admin.apikey=dummy

# Kafka
kafka.aiven.eessi.groupId=teammelosys-eessiMelding-consumer-local
kafka.aiven.eessi.topic=teammelosys.eessi.v1-local
kafka.aiven.soknad-mottak.groupid=teammelosys-soknad-mottak-consumer-local
kafka.aiven.soknad-mottak.topic=teammelosys.soknad-mottak.v1-local
kafka.aiven.a1-utstedt.topic=teammelosys.melosys-utstedt-a1.v1-local
kafka.aiven.manglende-fakturabetaling.topic=teammelosys.manglende-fakturabetaling-local
kafka.aiven.manglende-fakturabetaling.groupid=teammelosys.manglende-fakturabetaling-consumer-local
kafka.aiven.melosys-hendelser.topic=teammelosys.melosys-hendelser-local
kafka.aiven.skattehendelser.topic=teammelosys.skattehendelser.v1-local
kafka.aiven.skattehendelser.groupid=teammelosys.skattehendelser-consumer-local

# Entra (Azure AD)
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT=http://host.docker.internal:8082/isso/oauth2/v2.0/token
AZURE_APP_CLIENT_ID="lol"
AZURE_APP_CLIENT_SECRET="lol"

NAIS_CLUSTER_NAME=dev-fss
APP_NAME_PDL=pdl-api
APP_NAME_OPPGAVE=oppgave-q1
APP_NAME_SAF=saf
APP_NAME_MEDL=medlemskap-medl-api-q1
APP_NAME_ARBEIDSFORHOLD=aareg-services-nais
APP_NAME_INNTEKTSKOMPONENTEN=inntektskomponenten
APP_NAME_UTBETALING=sokos-utbetaldata

no.nav.security.jwt.client.registration.melosys-eessi.scope=melosys-localhost
no.nav.security.jwt.client.registration.faktureringskomponenten.scope=melosys-localhost
no.nav.security.jwt.client.registration.inntekt.scope=melosys-localhost
no.nav.security.jwt.client.registration.aareg.scope=melosys-localhost

# Logging av RestTemplate
logging.level.org.springframework.web.client.RestTemplate=INFO
