# OpenIDConnect (OpenAM)
OpenIdConnect.issoHost=https://isso-t.adeo.no/isso/oauth2
OpenIdConnect.issoIssuer=https://isso-t.adeo.no:443/isso/oauth2
OpenIdConnect.issoJwks=https://isso-t.adeo.no/isso/oauth2/connect/jwk_uri
OpenIdConnect.username=melosys-localhost
OpenIdConnect.password=#Kan hentes fra https://fasit.adeo.no/resources/2430072

# SecurityTokenService
securityTokenService.url=https://sts-t11.test.local/SecurityTokenServiceProvider/
systemuser.username=srvmelosys_u
systemuser.password=#Kan hentes fra https://fasit.adeo.no/resources/2888876

# AAREG
Arbeidsforhold_v3.url=https://modapp-t4.adeo.no/aareg-core/ArbeidsforholdService/v3

# EREG, Enhetsregisteret
Organisasjon_v4.url=https://modapp-t4.adeo.no/ereg/ws/OrganisasjonService/v4

# GSAK web service
BehandleSak_v1.url=https://wasapp-t4.adeo.no/nav-gsak-ws/BehandleSakV1
Sak_v1.url=https://wasapp-t4.adeo.no/nav-gsak-ws/SakV1

# Inntektskomponenten
Inntekt_v3.url=https://app-t4.adeo.no/inntektskomponenten-ws/inntekt/v3/Inntekt

# JOARK web service
Journal_v2.url=https://wasapp-t4.adeo.no/joark/Journal/v2
InngaaendeJournal_v1.url=https://wasapp-t4.adeo.no/joark/InngaaendeJournal/v1
BehandleInngaaendeJournal_v1.url=https://wasapp-t4.adeo.no/joark/BehandleInngaaendeJournal/v1

# TPS web service
Aktoer_v2.url=https://app-t4.adeo.no/aktoerid/AktoerService/v2
Person_v3.url=https://wasapp-t4.adeo.no/tpsws/ws/Person/v3

# Kodeverk service
Kodeverk_v2.url=https://modapp-t4.adeo.no/kodeverk/ws/Kodeverk/v2

# MEDL2
Medlemskap_v2.url=https://app-t11.adeo.no/medl2/ws/Medlemskap/v2
