#Token-validering
no.nav.security.jwt.issuer.isso.discovery-url=${OPENIDCONNECT_URL}/oauth2/.well-known/openid-configuration
no.nav.security.jwt.issuer.isso.accepted-audience=${ACCEPTED_AUDIENCE}
no.nav.security.jwt.issuer.isso.cookie-name=ID_token

# LDAP
ldap.url=${LDAP_URL}
ldap.username=${LDAP_USERNAME}
ldap.domain=${LDAP_DOMAIN}
ldap.password=${LDAP_PASSWORD}
ldap.userbasedn=${LDAP_USER_BASEDN}

# SecurityTokenService
securityTokenService.url=${SECURITYTOKENSERVICE_URL}
systemuser.username=${SRVMELOSYS_USERNAME}
systemuser.password=${SRVMELOSYS_PASSWORD}

melosys.security.melosys_ad_group=${MELOSYS_AD_GROUP}

# AAREG
Arbeidsforhold_v3.url=${VIRKSOMHET_ARBEIDSFORHOLD_V3_ENDPOINTURL}

# DOKSYS
Dokumentproduksjon_v3.url=${DOKUMENTPRODUKSJON_V3_ENDPOINTURL}
DistribuerJournalpost_v1.url=${DISTRIBUER_JOURNALPOST_V1_ENDPOINTURL}

# EREG, Enhetsregisteret
Organisasjon_v4.url=${VIRKSOMHET_ORGANISASJON_V4_ENDPOINTURL}

# GSAK web service
SakAPI_v1.url=${SAK_SAKER_URL}
OppgaveAPI_v1.url=${OPPGAVE_OPPGAVER_URL}

# Inntektskomponenten
Inntekt_v3.url=${VIRKSOMHET_INNTEKT_V3_ENDPOINTURL}

# JOARK web service
Journal_v3.url=${JOURNAL_V3_ENDPOINTURL}
JournalfoerInngaaende_v1.url=${JOURNALFOERINNGAAENDE_V1_URL}
JournalpostApi_v1.url=${JOURNALPOST_API_V1_URL}

# SAF
SAF.url=${SAF_URL}

# PDL
PDL.url=${PDL_URL}

# TPS web service
Aktoer_v2.url=${AKTOER_V2_ENDPOINTURL}
Person_v3.url=${VIRKSOMHET_PERSON_V3_ENDPOINTURL}

# Kodeverk service
KodeverkAPI_v1.url=${KODEVERK_REST_API_URL}

# MEDL2
medlemskap.rest.url=${MEDL_REST_API_URL}

# SBEH behandlingskjede
SakOgBehandling_v1.url=${SAKOGBEHANDLING_ENDPOINTURL}

# Utbetaling
Utbetaling_v1.url=${UTBETALING_V1_ENDPOINTURL}

# Inngangsvilkar
Inngangsvilkaar.url=http://melosys-inngangsvilkar/api

#REST-STS
REST_STS.url=${SECURITY_TOKEN_SERVICE_TOKEN_URL}

# Queue manager
queueManager.hostName=${MQGATEWAY02_HOSTNAME}
queueManager.port=${MQGATEWAY02_PORT}
queueManager.name=${MQGATEWAY02_NAME}
queueManager.channel=${MELOSYS_CHANNEL_NAME}
queueManager.useSsl=false

# SBEH queue
SBEH.queueName=${SBEH_SAKSBEHANDLING_QUEUENAME}
SBEH.username=srvappserver

# ABAC
no.nav.abac.url=${ABAC_PDP_ENDPOINT_URL}

# Melosys-eessi
MelosysEessi.url=http://melosys-eessi/api

# Melosys-soknad-mottak
MelosysSoknadMottak.url=http://melosys-soknad-mottak/api

# Melosys-dokgen
melosysdokgen.v1.url=http://melosys-dokgen/api/v1

# Melosys-trygdeavgift
melosystrygdeavgift.url=http://melosys-trygdeavgift/api

# Melosys-avgift-overforing
melosysavgiftoverforing.url=http://melosys-avgift-overforing/api

# Apikey til ProsessinstansAdminTjenste
Melosys-admin.apikey=${MELOSYS_ADMIN_API_KEY}

# Kafka
kafka.brokers=${KAFKA_BROKERS_URL}
kafka.eessi.groupid=melosys-eessiMelding-consumer
kafka.eessi.topic=${KAFKA_EESSIMELDING_TOPIC:privat-melosys-eessi-v1}
kafka.soknad-mottak.groupid=melosys-soknad-mottak-consumer
kafka.soknad-mottak.topic=${KAFKA_SOKNADMOTTAK_TOPIC:privat-melosys-soknad-mottak-v1}
kafka.a1-utstedt.topic=${KAFKA_UTSTEDT_A1_TOPIC:aapen-melosys-utstedtA1-v1}
kafka.fattetvedtak.topic=teammelosys.fattetvedtak.v1
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${systemuser.username}" password="${systemuser.password}";
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_SSL

# CORS
cors.allowOrigin=*.preprod.local, *.adeo.no
