spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=melosys
spring.datasource.password=melosyspwd

# Validerer Hibernate mapping
spring.jpa.hibernate.ddl-auto=validate

no.nav.security.jwt.issuer.aad.discovery-url=http://host.docker.internal:8082/isso/.well-known/openid-configuration
no.nav.security.jwt.issuer.aad.accepted-audience=melosys-localhost

# SecurityTokenService
securityTokenService.url=http://not-used
systemuser.username=srvmelosys
systemuser.password=dummy
stsPolicy.url=classpath:not-used

# AAREG
Arbeidsforhold_v3.url=http://localhost:8083/soap/services/aareg/v3
arbeidsforhold.rest.url=http://localhost:8083/aareg-services/api/v1/arbeidstaker/arbeidsforhold

# DOKSYS
Dokumentproduksjon_v3.url=http://localhost:8083/soap/services/dokumentproduksjon/v3
DistribuerJournalpost_v1.url=http://localhost:8083/rest/v1/distribuerjournalpost

# EREG, Enhetsregisteret
Organisasjon_v4.url=http://localhost:8083/soap/services/organisasjon/v4

# GSAK web service
SakAPI_v1.url=http://localhost:8083/api/v1/saker
OppgaveAPI_v1.url=http://localhost:8083/api/v1

# Inntektskomponenten
Inntekt_v3.url=http://localhost:8083/soap/services/inntekt/v3
inntekt.rest.url=http://localhost:8083/inntektskomponenten/rs/api/v1

# JournalpostAPI
JournalpostApi_v1.url=http://localhost:8083/rest/journalpostapi/v1

# SAF
SAF.url=http://localhost:8083

# PDL
PDL.url=http://localhost:8083/graphql

# TPS web service
Person_v3.url=http://localhost:8083/soap/services/tps/v3

# Kodeverk service
KodeverkAPI_v1.url=https://kodeverk.dev.adeo.no/api

# MEDL2
medlemskap.rest.url=http://localhost:8083/medl2/api/v1/medlemskapsunntak

# MICROSOFT GRAPH
microsoft.graph.rest.url=http://localhost:8083/graph/v1.0

# SBEH behandlingskjede
SakOgBehandling_v1.url=http://localhost:8083/soap/services/sakOgBehandling/v1

# Utbetaldata
Utbetaling_v1.url=http://localhost:8083/soap/services/utbetaling/v1
utbetaling_rest.url=http://localhost:8083/utbetaldata/api/v2/hent-utbetalingsinformasjon/intern

# Inngangsvilkar
Inngangsvilkaar.url=https://melosys-inngangsvilkar.intern.dev.nav.no/api

#REST-STS
REST_STS.url=http://localhost:8086/reststs

# Queue manager
queueManager.hostName=host.docker.internal
queueManager.port=41414
queueManager.name=SOB_QM
queueManager.channel=DEV.APP.SVRCONN
queueManager.useSsl=false

# ABAC
no.nav.abac.url=http://localhost:8083/asm-pdp/authorize

# Melosys-applikasjoner
# Faktureringskomponenten
faktureringskomponenten.url=http://localhost:8084

# For lokal testing:
#MelosysEessi.url=http://localhost:8081/api
MelosysSoknadMottak.url=http://localhost:8082/api
melosystrygdeavgift.url=http://localhost:8085/api

MelosysEessi.url=http://localhost:8083/api
melosysdokgen.v1.url=https://melosys-dokgen.intern.dev.nav.no/api/v1
# For lokal testing:
#MelosysEessi.url=http://localhost:8081/api
#melosysdokgen.v1.url=http://localhost:8888/api/v1

# Apikey til ProsessinstansAdminTjenste
Melosys-admin.apikey=dummy


# Kafka
kafka.aiven.eessi.groupId=teammelosys-eessiMelding-consumer-local
kafka.aiven.eessi.topic=teammelosys.eessi.v1-local
kafka.aiven.soknad-mottak.groupid=teammelosys-soknad-mottak-consumer-local
kafka.aiven.soknad-mottak.topic=teammelosys.soknad-mottak.v1-local
kafka.aiven.a1-utstedt.topic=teammelosys.melosys-utstedt-a1.v1-local
kafka.aiven.manglende-fakturabetaling.topic=teammelosys.manglende-fakturabetaling-local
kafka.aiven.manglende-fakturabetaling.groupid=teammelosys.manglende-fakturabetaling-consumer-local

no.nav.security.jwt.client.registration.pdl.token-endpoint-url=http://host.docker.internal:8082/isso/oauth2/v2.0/token
no.nav.security.jwt.client.registration.pdl.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.pdl.scope=api://dev-fss.pdl.pdl-api/.default
no.nav.security.jwt.client.registration.pdl.authentication.client-id="lol"
no.nav.security.jwt.client.registration.pdl.authentication.client-secret="lol"
no.nav.security.jwt.client.registration.pdl.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.oppgave.token-endpoint-url=http://host.docker.internal:8082/isso/oauth2/v2.0/token
no.nav.security.jwt.client.registration.oppgave.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.oppgave.scope=api://dev-fss.oppgavehandtering.oppgave-q1/.default
no.nav.security.jwt.client.registration.oppgave.authentication.client-id="lol"
no.nav.security.jwt.client.registration.oppgave.authentication.client-secret="lol"
no.nav.security.jwt.client.registration.oppgave.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.saf.token-endpoint-url=http://host.docker.internal:8082/isso/oauth2/v2.0/token
no.nav.security.jwt.client.registration.saf.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.saf.scope=api://dev-fss.teamdokumenthandtering.saf/.default
no.nav.security.jwt.client.registration.saf.authentication.client-id="lol"
no.nav.security.jwt.client.registration.saf.authentication.client-secret="lol"
no.nav.security.jwt.client.registration.saf.authentication.client-auth-method=client_secret_basic


no.nav.security.jwt.client.registration.medl.token-endpoint-url=http://host.docker.internal:8082/isso/oauth2/v2.0/token
no.nav.security.jwt.client.registration.medl.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.medl.scope=api://dev-fss.team-rocket.medlemskap-medl-api-q1/.default
no.nav.security.jwt.client.registration.medl.authentication.client-id="lol"
no.nav.security.jwt.client.registration.medl.authentication.client-secret="lol"
no.nav.security.jwt.client.registration.medl.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.sokos-utbetaldata.token-endpoint-url=http://host.docker.internal:8082/isso/oauth2/v2.0/token
no.nav.security.jwt.client.registration.sokos-utbetaldata.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.sokos-utbetaldata.scope=api://dev-fss.okonomi.sokos-utbetaldata/.default
no.nav.security.jwt.client.registration.sokos-utbetaldata.authentication.client-id="test"
no.nav.security.jwt.client.registration.sokos-utbetaldata.authentication.client-secret="test"
no.nav.security.jwt.client.registration.sokos-utbetaldata.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.melosys-eessi.token-endpoint-url=http://host.docker.internal:8082/isso/oauth2/v2.0/token
no.nav.security.jwt.client.registration.melosys-eessi.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.melosys-eessi.scope=api://dev-fss.teammelosys.melosys-eessi-q1/.default
no.nav.security.jwt.client.registration.melosys-eessi.authentication.client-id="lol"
no.nav.security.jwt.client.registration.melosys-eessi.authentication.client-secret="lol"
no.nav.security.jwt.client.registration.melosys-eessi.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.faktureringskomponenten.token-endpoint-url=http://host.docker.internal:8082/isso/token
no.nav.security.jwt.client.registration.faktureringskomponenten.grant-type=urn:ietf:params:oauth:grant-type:jwt-bearer
no.nav.security.jwt.client.registration.faktureringskomponenten.scope=melosys-localhost
no.nav.security.jwt.client.registration.faktureringskomponenten.authentication.client-id=lol
no.nav.security.jwt.client.registration.faktureringskomponenten.authentication.client-secret=lol
no.nav.security.jwt.client.registration.faktureringskomponenten.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.graph.token-endpoint-url=http://host.docker.internal:8082/isso/token
no.nav.security.jwt.client.registration.graph.grant-type=client_credentials
no.nav.security.jwt.client.registration.graph.scope=https://graph.microsoft.com/.default
no.nav.security.jwt.client.registration.graph.authentication.client-id=lol
no.nav.security.jwt.client.registration.graph.authentication.client-secret=lol
no.nav.security.jwt.client.registration.graph.authentication.client-auth-method=client_secret_basic

no.nav.security.jwt.client.registration.inntekt.token-endpoint-url=http://host.docker.internal:8082/isso/token
no.nav.security.jwt.client.registration.inntekt.grant-type=client_credentials
no.nav.security.jwt.client.registration.inntekt.scope=melosys-localhost
no.nav.security.jwt.client.registration.inntekt.authentication.client-id=lol
no.nav.security.jwt.client.registration.inntekt.authentication.client-secret=lol
no.nav.security.jwt.client.registration.inntekt.authentication.client-auth-method=client_secret_basic

# Logging av RestTemplate
logging.level.org.springframework.web.client.RestTemplate=INFO
