spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@d26dbfl029.test.local:1521/melosys_t8
spring.datasource.username=MELOSYS_T8
#spring.datasource.password=Kan hentes fra https://fasit.adeo.no/resources/3832109

# Flyway og migrering av testdata
spring.flyway.locations=classpath:db/migration,classpath:db/local/testdata

# Validerer Hibernate mapping
spring.jpa.hibernate.ddl-auto=validate

# OpenIDConnect (OpenAM)
#security.oidc.issoHost=https://isso-t.adeo.no/isso/oauth2
#security.oidc.discoveryUrl=https://isso-t.adeo.no/isso/oauth2/.well-known/openid-configuration
#security.oidc.username=melosys-localhost
#security.oidc.password=Kan hentes fra https://fasit.adeo.no/resources/2430072

# LDAP
ldap.url=ldap://ldapgw.test.local
ldap.username=srvmelosys
ldap.domain=TEST.LOCAL
#ldap.password=Kan hentes fra https://fasit.adeo.no/resources/4976531
ldap.user.basedn=ou\=NAV,ou\=BusinessUnits,dc\=test,dc\=local

# SecurityTokenService
securityTokenService.url=https://sts-t8.test.local/SecurityTokenServiceProvider/
systemuser.username=srvmelosys
#systemuser.password=Kan hentes fra https://fasit.adeo.no/resources/4976531

# AAREG
Arbeidsforhold_v3.url=https://modapp-t8.adeo.no/aareg-core/ArbeidsforholdService/v3

# DOKSYS
Dokumentproduksjon_v3.url=https://dokprod-t8.nais.preprod.local/dokprod/ws/dokumentproduksjon/v3
DistribuerJournalpost_v1.url=https://dokdistfordeling-t8.nais.preprod.local/rest/v1/distribuerjournalpost

# EREG, Enhetsregisteret
Organisasjon_v4.url=https://modapp-t8.adeo.no/ereg/ws/OrganisasjonService/v4

# GSAK web service
SakAPI_v1.url=https://sak-t8.nais.preprod.local/api/v1/saker
OppgaveAPI_v1.url=https://oppgave-t8.nais.preprod.local/api/v1/oppgaver

# Inntektskomponenten
Inntekt_v3.url=https://app-t8.adeo.no/inntektskomponenten-ws/inntekt/v3/Inntekt

# JOARK web service
Journal_v3.url=https://wasapp-t8.adeo.no/joark/Journal/v3
InngaaendeJournal_v1.url=https://wasapp-t8.adeo.no/joark/InngaaendeJournal/v1
JournalfoerInngaaende_v1.url=https://dokarkiv-t8.nais.preprod.local/rest/journalfoerinngaaende/v1
JournalpostApi_v1.url=https://dokarkiv-t8.nais.preprod.local/rest/journalpostapi/v1/journalpost

# TPS web service
Aktoer_v2.url=https://app-t8.adeo.no/aktoerregister/ws/Aktoer/v2
Person_v3.url=https://wasapp-t8.adeo.no/tpsws/ws/Person/v3

# Kodeverk service
KodeverkAPI_v1.url=https://kodeverk.nais.preprod.local/api

# MEDL2
Medlemskap_v2.url=https://app-t8.adeo.no/medl2/ws/Medlemskap/v2
BehandleMedlemskap_v2.url=https://app-t8.adeo.no/medl2/ws/BehandleMedlemskap/v2

# SBEH behandlingskjede
SakOgBehandling_v1.url=https://modapp-t8.adeo.no/sakogbehandling/ws/SakOgBehandling_v1

# Utbetaling
Utbetaling_v1.url=https://wasapp-t8.adeo.no/nav-utbetaldata-ws/virksomhet/Utbetaling_v1

# Regelmodul
melosys.service.regelmodul.url=http://localhost:8081/api/lovvalg

#REST-STS
REST_STS.url=https://security-token-service-t4.nais.preprod.local/rest/v1/sts/token

# Queue manager
queueManager.hostName=d26apvl258.test.local
queueManager.port=1412
queueManager.name=MTXLSC02
queueManager.channel=T8_MELOSYS
queueManager.useSsl=false

# SBEH queue
SBEH.queueName=QA.T5_SBEH.SAKSBEHANDLING

# ABAC
no.nav.abac.url=https://wasapp-t8.adeo.no/asm-pdp/authorize

# Melosys-eessi
MelosysEessi.url=http://localhost:8081/api
MelosysEessi.forsokSendSed=true

# Kafka
kafka.brokers=d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443
kafka.groupid=melosys-eessiMelding-consumer-local
kafka.topic.eessi=privat-melosys-eessi-v1-local

#melosys.security.melosys_ad_group=hentes fra vault med key MELOSYS_AD_GROUP

no.nav.security.jwt.issuer.isso.discovery-url=${OPENIDCONNECT_URL}/oauth2/.well-known/openid-configuration
no.nav.security.jwt.issuer.isso.accepted-audience=melosys-localhost