spring.main.banner-mode=off

# Server
#FIXME context-path kommer med BIG-IP config (i fasit) og krever en endring i frontend.
#server.context-path=/melosys
server.use-forward-headers=true

# Bruk profilen local for å kjøre lokalt
spring.profiles.active=nais,mocking,test

# Actuator og metrikker
management.context-path=/internal
management.security.enabled=false
management.health.diskspace.enabled=false
management.metrics.enable[process.start.time]=false
management.metrics.enable[jvm.threads.peak]=false
management.metrics.enable[jvm.threads.daemon]=false
management.metrics.enable[jvm.classes.loaded]=false
management.metrics.enable[jvm.classes.unloaded]=false

# Datasource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${melosysDB.url}
spring.datasource.username=${melosysDB.username}
spring.datasource.password=${melosysDB.password}

# Hikari connection pool
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5

# Hibernate dialect
spring.jpa.database-platform=no.nav.melosys.Oracle12cXmlClobDialect

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.serialization.write-dates-as-timestamps=false