spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/MEL
spring.datasource.username=melosys
spring.datasource.password=melosyspwd

# Validerer Hibernate mapping
spring.jpa.hibernate.ddl-auto=validate

#Token-validering
no.nav.security.jwt.issuer.isso.discovery-url=http://host.docker.internal:8082/isso/.well-known/openid-configuration
no.nav.security.jwt.issuer.isso.accepted-audience=melosys-localhost
no.nav.security.jwt.issuer.isso.cookie-name=ID_token

# LDAP
ldap.url=ldap://localhost:8389/
ldap.userbasedn=ou\=NAV,ou\=BusinessUnits,dc\=test,dc\=local

# SecurityTokenService
securityTokenService.url=http://not-used
systemuser.username=srvmelosys
systemuser.password=dummy

melosys.security.melosys_ad_group=0000-GA-MELOSYS

# AAREG
Arbeidsforhold_v3.url=http://localhost:8083/soap/services/aareg/v3
arbeidsforhold.rest.url=http://localhost:8083/aareg-services/api/v1/arbeidstaker/arbeidsforhold

# DOKSYS
Dokumentproduksjon_v3.url=http://localhost:8083/soap/services/dokumentproduksjon/v3
DistribuerJournalpost_v1.url=http://localhost:8083/rest/v1/distribuerjournalpost

# EREG, Enhetsregisteret
Organisasjon_v4.url=http://localhost:8083/soap/services/organisasjon/v4

# GSAK web service
SakAPI_v1.url=http://localhost:8083/api/v1/saker
OppgaveAPI_v1.url=http://localhost:8083/api/v1

# Inntektskomponenten
Inntekt_v3.url=http://localhost:8083/soap/services/inntekt/v3

# JournalpostAPI
JournalpostApi_v1.url=http://localhost:8083/rest/journalpostapi/v1

# SAF
SAF.url=http://localhost:8083

# PDL
PDL.url=http://localhost:8083/graphql

# TPS web service
Person_v3.url=http://localhost:8083/soap/services/tps/v3

# Kodeverk service
KodeverkAPI_v1.url=https://kodeverk.dev.adeo.no/api

# MEDL2
medlemskap.rest.url=http://localhost:8083/medl2/api/v1/medlemskapsunntak

# SBEH behandlingskjede
SakOgBehandling_v1.url=http://localhost:8083/soap/services/sakOgBehandling/v1

# Utbetaling TODO
Utbetaling_v1.url=http://localhost:8083/soap/services/utbetaling/v1

# Inngangsvilkar
Inngangsvilkaar.url=https://melosys-inngangsvilkar.dev.intern.nav.no/api

#REST-STS
REST_STS.url=http://localhost:8083/rest/v1/sts/token

# Queue manager
queueManager.hostName=host.docker.internal
queueManager.port=41414
queueManager.name=SOB_QM
queueManager.channel=DEV.APP.SVRCONN
queueManager.useSsl=false

# SBEH queue
SBEH.queueName=DEV.QUEUE.1
SBEH.username=mqm

# ABAC
no.nav.abac.url=http://localhost:8083/asm-pdp/authorize

# Melosys-applikasjoner TODO
MelosysEessi.url=http://localhost:8083/api
MelosysSoknadMottak.url=http://localhost:8082/api
melosystrygdeavgift.url=https://melosys-trygdeavgift.dev.adeo.no/api
melosysdokgen.v1.url=https://melosys-dokgen.dev.adeo.no/api/v1
melosysavgiftoverforing.url=https://melosys-avgift-overforing.dev.adeo.no/api

# Apikey til ProsessinstansAdminTjenste
Melosys-admin.apikey=dummy

# Kafka
kafka.onprem.brokers=localhost:29092
kafka.eessi.groupid=melosys-eessiMelding-consumer-local
kafka.eessi.topic=privat-melosys-eessi-v1-local
kafka.soknad-mottak.groupid=melosys-soknad-mottak-consumer-local
kafka.soknad-mottak.topic=privat-melosys-soknad-mottak-local
kafka.a1-utstedt.topic=aapen-melosys-utstedtA1-v1-local
kafka.fattetvedtak.topic=teammelosys.fattetvedtak.v1-local
