#Token-validering
no.nav.security.jwt.issuer.aad.discoveryurl=${AZURE_APP_WELL_KNOWN_URL}
no.nav.security.jwt.issuer.aad.accepted-audience=${AZURE_APP_CLIENT_ID}

systemuser.username=${SRV_USERNAME}
systemuser.password=${SRV_PASSWORD}

# Soap-klient policy
stsPolicy.url=classpath:stsPolicy.xml

# AAREG
arbeidsforhold.rest.url=${ARBEIDSFORHOLD_REST_V1_ENDPOINTURL}

# DOKSYS
Dokumentproduksjon_v3.url=${DOKUMENTPRODUKSJON_V3_ENDPOINTURL}
DistribuerJournalpost_v1.url=${DISTRIBUER_JOURNALPOST_V1_ENDPOINTURL}

# EREG, Enhetsregisteret
ereg.rest.url=${EREG_REST_V2_ENDPOINTURL}

# GSAK web service
SakAPI_v1.url=${SAK_SAKER_URL}
OppgaveAPI_v1.url=${OPPGAVE_OPPGAVER_URL}

# Inntektskomponenten
inntekt.rest.url=${INNTEKT_REST_V1_ENDPOINTURL}

# JournalpostAPI
JournalpostApi_v1.url=${JOURNALPOST_API_V1_URL}

# SAF
SAF.url=${SAF_URL}

# PDL
PDL.url=${PDL_URL}

# TPS web service
Person_v3.url=${VIRKSOMHET_PERSON_V3_ENDPOINTURL}

# Kodeverk service
KodeverkAPI_v1.url=${KODEVERK_REST_API_URL}

# MEDL2
medlemskap.rest.url=${MEDL_REST_API_URL}

# MICROSOFT GRAPH
microsoft.graph.rest.url=${MICROSOFT_GRAPH_REST_URL}

# SBEH behandlingskjede
SakOgBehandling_v1.url=${SAKOGBEHANDLING_ENDPOINTURL}

# Utbetaldata
Utbetaling_v1.url=${UTBETALING_V1_ENDPOINTURL}
utbetaling_rest.url=${UTBETALING_V2_ENDPOINTURL}

# Inngangsvilkar
Inngangsvilkaar.url=${MELOSYS_INNGANGSVILKAR_URL}

#REST-STS
REST_STS.url=${SECURITY_TOKEN_SERVICE_TOKEN_URL}

# SBEH queue
SBEH.queueName=${SBEH_SAKSBEHANDLING_QUEUENAME}
SBEH.username=srvappserver

# ABAC
no.nav.abac.url=${ABAC_PDP_ENDPOINT_URL}

# Melosys-eessi
MelosysEessi.url=${MELOSYS_EESSI_URL}

# Melosys-soknad-mottak
MelosysSoknadMottak.url=${MELOSYS_SOKNAD_MOTTAK_URL}

# Melosys-dokgen
melosysdokgen.v1.url=${MELOSYS_DOKGEN_URL}

# Melosys-trygdeavgift
melosystrygdeavgift.url=${MELOSYS_TRYGDEAVGIFT_URL}

# Faktureringskomponenten
faktureringskomponenten.url=${FAKTURERINGSKOMPONENTEN_URL}

# Apikey til ProsessinstansAdminTjenste
Melosys-admin.apikey=${MELOSYS_ADMIN_API_KEY}

#Unleash
unleash.token=${UNLEASH_SERVER_API_TOKEN}

# Kafka
kafka.aiven.eessi.groupId=teammelosys-eessiMelding-consumer
kafka.aiven.eessi.topic=${KAFKA_AIVEN_EESSIMELDING_TOPIC:teammelosys.eessi.v1}
kafka.aiven.soknad-mottak.groupid=teammelosys-soknad-mottak-consumer
kafka.aiven.soknad-mottak.topic=${KAFKA_AIVEN_SOKNADMOTTATT_TOPIC:teammelosys.soknad-mottak.v1}
kafka.aiven.a1-utstedt.topic=${KAFKA_AIVEN_UTSTEDT_A1_TOPIC:teammelosys.melosys-utstedt-a1.v1}
kafka.aiven.manglende-fakturabetaling.topic=${KAFKA_AIVEN_MANGLENDE_FAKTURABETALING_TOPIC:teammelosys.manglende-fakturabetaling.v1}
kafka.aiven.manglende-fakturabetaling.groupid=teammelosys.manglende-fakturabetaling-consumer
kafka.aiven.melosys-hendelser.topic=${KAFKA_AIVEN_MELOSYS_HENDELSER:teammelosys.melosys-hendelser.v1}
kafka.aiven.skattehendelser.topic=${KAFKA_AIVEN_SKATTEHENDELSER:teammelosys.skattehendelser.v1}
kafka.aiven.skattehendelser.groupid=teammelosys.skattehendelser-consumer

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${systemuser.username}" password="${systemuser.password}";
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_SSL

# CORS
cors.allowOrigin=*.preprod.local, *.adeo.no

# Client scopes for Entra (Azure AD)
no.nav.security.jwt.client.registration.pdl.scope=api://${NAIS_CLUSTER_NAME}.pdl.${APP_NAME_PDL}/.default
no.nav.security.jwt.client.registration.oppgave.scope=api://${NAIS_CLUSTER_NAME}.oppgavehandtering.${APP_NAME_OPPGAVE}/.default
no.nav.security.jwt.client.registration.saf.scope=api://${NAIS_CLUSTER_NAME}.teamdokumenthandtering.${APP_NAME_SAF}/.default
no.nav.security.jwt.client.registration.medl.scope=api://${NAIS_CLUSTER_NAME}.team-rocket.${APP_NAME_MEDL}/.default
no.nav.security.jwt.client.registration.melosys-eessi.scope=api://${NAIS_CLUSTER_NAME}.teammelosys.${APP_NAME_MELOSYS_EESSI}/.default
no.nav.security.jwt.client.registration.faktureringskomponenten.scope=api://${NAIS_CLUSTER_NAME_FAKTURERINGSKOMPONENTEN}.teammelosys.${APP_NAME_FAKTURERINGSKOMPONENTEN}/.default
no.nav.security.jwt.client.registration.graph.scope=https://graph.microsoft.com/.default
no.nav.security.jwt.client.registration.sokos-utbetaldata.scope=api://${NAIS_CLUSTER_NAME}.okonomi.${APP_NAME_UTBETALING}/.default
no.nav.security.jwt.client.registration.inntekt.scope=api://${NAIS_CLUSTER_NAME}.team-inntekt.${APP_NAME_INNTEKTSKOMPONENTEN}/.default
no.nav.security.jwt.client.registration.aareg.scope=api://${NAIS_CLUSTER_NAME}.arbeidsforhold.${APP_NAME_ARBEIDSFORHOLD}/.default

http.proxy=${HTTP_PROXY}
