spring.main.banner-mode=off

# Server
#FIXME context-path /melosys brukes for å kjøre lokalt:
#server.context-path=/melosys
server.use-forward-headers=true

# Bruk profilen local for å kjøre lokalt
spring.profiles.active=nais

# Drop and create, loads import.sql
spring.jpa.hibernate.ddl-auto=validate

# Actuator
management.context-path=/internal
management.security.enabled=false
management.info.defaults.enabled=false

# Datasource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${melosysDB.url}
spring.datasource.username=${melosysDB.username}
spring.datasource.password=${melosysDB.password}

# Hikari connection pool
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5

# Hibernate dialect
spring.jpa.database-platform=no.nav.melosys.Oracle12cXmlClobDialect

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate=info
#logging.level.=error