package no.nav.melosys.service.oppgave;

public enum OppgaveBehandlingstema {
    EU_EOS_LAND("ab0424"),
    AVTALELAND("ab0387"),
    UTENFOR_AVTALELAND("ab0388"),
    PENSJONIST_ELLER_UFORETRYGDET("ab0355"),
    YRKESAKTIV("ab0462"),
    ANMODNING_UNNTAK("ab0460"),
    REGISTRERING_UNNTAK("ab0461"),
    EU_EOS_YRKESAKTIV("ab0483"),
    EU_EOS_PENSJONIST_ELLER_UFORETRYGDET("ab0480"),
    EU_EOS_IKKE_YRKESAKTIV("ab0481"),
    EU_EOS_NORGE_ER_UTPEKT_SOM_LOVVALGSLAND("ab0482"),
    EU_EOS_FORESPORSEL_OM_TRYGDETID("ab0479"),
    UTENFOR_AVTALAND_YRKESAKTIV("ab0484"),
    UTENFOR_AVTALAND_PENSJONIST_ELLER_UFORETRYGDET("ab0485"),
    UTENFOR_AVTALAND_IKKE_YRKESAKTIV("ab0486"),
    AVTALAND_IKKE_YRKESAKTIV("ab0475"),
    AVTALAND_PENSJONIST_ELLER_UFORETRYGDET("ab0476"),
    AVTALAND_YRKESAKTIV("ab0477"),
    UTENFOR_AVTALAND_SOKNAD_OM_UNNTAK("ab0493"),
    EU_EOS_MELDING_OM_UNNTAK_UNNTAK("ab0490"),
    EU_EOS_SOKNAD_OM_UNNTAK("ab0491"),
    EU_EOS_FORESPORSEL_FRA_TRYGDEMYNDIGHET("ab0492"),
    AVTALAND_FORESPORSEL_FRA_TRYGDEMYNDIGHET("ab0478"),
    AVTALAND_MELDING_OM_UNNTAK("ab0488"),
    AVTALAND_SOKNAD_OM_UNNTAK("ab0489");
    private final String kode;

    OppgaveBehandlingstema(String kode) {
        this.kode = kode;
    }

    public String getKode() {
        return kode;
    }
}
