alter table BEHANDLING modify id generated by default as identity;

INSERT INTO BEHANDLING (ID, SAKSNUMMER, STATUS, BEH_TYPE, REGISTRERT_DATO, ENDRET_DATO)
VALUES(3, 'MELTEST-1', 'OPPR', 'SKND', TIMESTAMP '2017-10-19 14:35:54.000000', SYSDATE);

alter table BEHANDLING modify id generated always as identity (START WITH LIMIT VALUE);

