alter table FAGSAK modify id generated by default as identity;

INSERT INTO FAGSAK (ID, GSAK_SAKSNUMMER, FAGSAK_TYPE, STATUS, REGISTRERT_DATO, ENDRET_DATO)
VALUES(3, '123', 'A1', 'OPPR', TIMESTAMP '2017-10-19 12:31:36.000000', SYSDATE);

alter table FAGSAK modify id generated always as identity (START WITH LIMIT VALUE);