alter table AKTOER modify id generated by default as identity;

INSERT INTO AKTOER (ID, SAKSNUMMER, AKTOER_ID, ORGNR, ROLLE) VALUES(1, 'MELTEST-1', '16FJERNET', NULL, 'BRUKER');

alter table AKTOER modify id generated always as identity (START WITH LIMIT VALUE);