CREATE TABLE saksopplysning (
    id              NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
    behandling_id   NUMBER(19)     NOT NULL,
    opplysning_type VARCHAR2(99)   NOT NULL,
    versjon         VARCHAR2(99)   NOT NULL,
    kilde           VARCHAR2(99)   NOT NULL,
    registrert_dato TIMESTAMP      NOT NULL,
    endret_dato     TIMESTAMP      NOT NULL,
    dokument_xml    XMLTYPE        NOT NULL,
    intern_xml      XMLTYPE        ,
    CONSTRAINT pk_saksopplysning PRIMARY KEY (id)
);

CREATE INDEX idx_saksopplysning_behandling ON saksopplysning(behandling_id,opplysning_type);

CREATE TABLE saksopplysning_type (
    kode        VARCHAR2(99)  NOT NULL,
    navn        VARCHAR2(99)  NOT NULL,
    CONSTRAINT pk_saksopplysning_type PRIMARY KEY (kode)
);

INSERT INTO saksopplysning_type (kode, navn) VALUES ('ARBFORH', 'Arbeidsforhold');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('INNTK', 'Inntekt');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('MEDL', 'Medlemskap');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('ORG', 'Arbeidsgiver');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('PERSHIST', 'Personhistorikk');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('PERSOPL', 'Personopplysninger');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('SOB_SAK', 'Sak og behandling-sak');
INSERT INTO saksopplysning_type (kode, navn) VALUES ('SØKNAD', 'Søknad');


CREATE TABLE saksopplysning_kilde (
    kode        VARCHAR2(99)  NOT NULL,
    navn        VARCHAR2(99)  NOT NULL,
    CONSTRAINT pk_saksopplysning_kilde PRIMARY KEY (kode)
);

INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('AAREG', 'Aa-registeret');
INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('EREG', 'Enhetsregisteret');
INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('INNTK', 'Inntektskomponenten');
INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('MEDL', 'Medlemskapsunntak');
INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('SBH', 'Saksbehandler');
INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('SOB', 'Sak og behandling');
INSERT INTO saksopplysning_kilde (kode, navn) VALUES ('TPS', 'Folkeregisteret');

ALTER TABLE saksopplysning ADD CONSTRAINT fk_saksopplysning_behandling FOREIGN KEY (behandling_id) REFERENCES behandling;
ALTER TABLE saksopplysning ADD CONSTRAINT fk_saksopplysning_type FOREIGN KEY (opplysning_type) REFERENCES saksopplysning_type;
ALTER TABLE saksopplysning ADD CONSTRAINT fk_saksopplysning_kilde FOREIGN KEY (kilde) REFERENCES saksopplysning_kilde;
