-- Fjern trygdeavgiftsgrunnlag_id fra INNTEKTSPERIODE og SKATTEFORHOLD_TIL_NORGE
ALTER TABLE INNTEKTSPERIODE
    DROP COLUMN trygdeavgiftsgrunnlag_id;
ALTER TABLE SKATTEFORHOLD_TIL_NORGE
    DROP COLUMN trygdeavgiftsgrunnlag_id;
DROP TABLE TRYGDEAVGIFTSGRUNNLAG;
