-- Steg 1: Legg til TYPE i BEHANDLINGSRESULTAT
ALTER TABLE BEHANDLINGSRESULTAT ADD (TRYGDEAVGIFT_TYPE VARCHAR2(99));

-- Steg 2: Migrere BEHANDLINGSRESULTAT med TYPE fra FASTSATT_TRYGDEAVGIFT
UPDATE BEHANDLINGSRESULTAT behandlingsresultat
SET behandlingsresultat.TRYGDEAVGIFT_TYPE = (
    SELECT fastsattTrygdeavgift.TYPE
    FROM MEDLEM_AV_FOLKETRYGDEN medlemAvFolketrygden
             JOIN FASTSATT_TRYGDEAVGIFT fastsattTrygdeavgift ON medlemAvFolketrygden.ID = fastsattTrygdeavgift.MEDLEM_AV_FOLKETRYGDEN_ID
    WHERE behandlingsresultat.BEHANDLING_ID = medlemAvFolketrygden.BEH_RESULTAT_ID
)
WHERE EXISTS (
    SELECT 1
    FROM MEDLEM_AV_FOLKETRYGDEN medlemAvFolketrygden
             JOIN FASTSATT_TRYGDEAVGIFT fastsattTrygdeavgift ON medlemAvFolketrygden.ID = fastsattTrygdeavgift.MEDLEM_AV_FOLKETRYGDEN_ID
    WHERE behandlingsresultat.BEHANDLING_ID = medlemAvFolketrygden.BEH_RESULTAT_ID
);

-- Step 3: Legg til MEDLEMSKAPSPERIODE i BEHANDLINGSRESULTAT
ALTER TABLE MEDLEMSKAPSPERIODE ADD (BEHANDLINGSRESULTAT_ID NUMBER);

ALTER TABLE MEDLEMSKAPSPERIODE
    ADD CONSTRAINT fk_beh_resultat_id
        FOREIGN KEY (BEHANDLINGSRESULTAT_ID) REFERENCES BEHANDLINGSRESULTAT (BEHANDLING_ID);


UPDATE MEDLEMSKAPSPERIODE medlemskapsperiode
SET medlemskapsperiode.BEHANDLINGSRESULTAT_ID = (
    SELECT medlemAvFolketrygden.BEH_RESULTAT_ID
    FROM MEDLEM_AV_FOLKETRYGDEN medlemAvFolketrygden
    WHERE medlemskapsperiode.MEDLEM_AV_FOLKETRYGDEN_ID = medlemAvFolketrygden.ID
);

ALTER TABLE MEDLEMSKAPSPERIODE DROP COLUMN MEDLEM_AV_FOLKETRYGDEN_ID;
ALTER TABLE TRYGDEAVGIFTSPERIODE DROP COLUMN FASTSATT_TRYGDEAVGIFT_ID;

-- Steg 4: Drop FASTSATT_TRYGDEAVGIFT og MEDLEM_AV_FOLKETRYGDEN
DROP TABLE FASTSATT_TRYGDEAVGIFT CASCADE CONSTRAINTS;
DROP TABLE MEDLEM_AV_FOLKETRYGDEN CASCADE CONSTRAINTS;
