CREATE TABLE FAGSAK_TEMA
(
    KODE VARCHAR2(20) NOT NULL,
    NAVN VARCHAR2(99) NOT NULL,
    CONSTRAINT PK_FAGSAK_TEMA PRIMARY KEY (KODE)
);
INSERT INTO FAGSAK_TEMA (KODE, NAVN) VALUES ('MEDLEMSKAP_LOVVALG', 'Medlemskap og lovvalg');
INSERT INTO FAGSAK_TEMA (KODE, NAVN) VALUES ('UNNTAK', 'Unntak');
INSERT INTO FAGSAK_TEMA (KODE, NAVN) VALUES ('TRYGDEAVGIFT', 'Trygdeavgift');
