UPDATE vilkaarsresultat
SET vilkaar = 'VESENTLIG_VIRKSOMHET'
WHERE vilkaar = 'ART12_1_VESENTLIG_VIRKSOMHET';

UPDATE vilkaarsresultat
SET vilkaar = 'FORUTGAAENDE_MEDLEMSKAP'
WHERE vilkaar = 'ART12_1_FORUTGAAENDE_MEDLEMSKAP';

UPDATE vilkaarsresultat
SET vilkaar = 'NORMALT_DRIVER_VIRKSOMHET'
WHERE vilkaar = 'ART12_2_NORMALT_DRIVER_VIRKSOMHET';
