INSERT INTO BEHANDLING_TEMA (KODE, NAVN) VALUES ('FORESPØRSEL_TRYGDEMYNDIGHET', 'Forespørsel fra trygdemyndighet');
INSERT INTO BEHANDLING_TEMA (KODE, NAVN) VALUES ('UNNTAK_MEDLEMSKAP', 'Unntak fra medlemskap');
INSERT INTO BEHANDLING_TEMA (KODE, NAVN) VALUES ('REGISTRERING_UNNTAK', 'Registrering unntak');
INSERT INTO BEHANDLING_TEMA (KODE, NAVN) VALUES ('PENSJONIST', 'Pensjonist/uføretrygdet');
