-- Fjerner LAGRE_SAKSOPPLYSNINGER_SØKNAD prosesssteg.
-- Lagring av mottatte opplysninger gjøres nå i OPPRETT_SAK_OG_BEHANDLING_SØKNAD-steget i stedet.
-- DELETE/UPDATE vil ikke treffe noen rader i produksjon på dette tidspunktet,
-- men rydder opp i eventuelle rader i dev/test-miljøer.
DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG = 'LAGRE_SAKSOPPLYSNINGER_SØKNAD';
UPDATE PROSESSINSTANS SET SIST_FULLFORT_STEG = 'OPPRETT_SAK_OG_BEHANDLING_SØKNAD' WHERE SIST_FULLFORT_STEG = 'LAGRE_SAKSOPPLYSNINGER_SØKNAD';
DELETE FROM PROSESS_STEG WHERE KODE = 'LAGRE_SAKSOPPLYSNINGER_SØKNAD';
