-- MELOSYS-7588: Ny grunnlag-tabell for 1:N-relasjon mellom trygdeavgiftsperiode og grunnlag
--
-- ON DELETE CASCADE på trygdeavgiftsperiode_id: Når trygdeavgiftsperiode slettes
-- (orphan removal), sletter databasen automatisk tilhørende grunnlag-rader.
--
-- ON DELETE SET NULL på avgiftspliktig-periode FK-er (medlemskap/lovvalg/helseutgift):
-- Hibernate kan slette Medlemskapsperiode/Lovvalgsperiode/HelseutgiftDekkesPeriode
-- før grunnlag-raden. SET NULL lar slettingen gå gjennom; grunnlag-raden
-- ryddes opp etterpå via ON DELETE CASCADE på trygdeavgiftsperiode_id.
--
-- NB: inntektsperiode_id og skatteforhold_id har IKKE ON DELETE CASCADE.
-- Disse har cascade=PERSIST+MERGE (ikke REMOVE) i JPA for å unngå ORA-02292.
-- Orphaned rader i inntektsperiode/skatteforhold_til_norge ryddes opp manuelt.

CREATE TABLE trygdeavgiftsperiode_grunnlag
(
    id                           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    trygdeavgiftsperiode_id      NUMBER(19) NOT NULL,
    medlemskapsperiode_id        NUMBER(19),
    lovvalgsperiode_id           NUMBER(19),
    helseutgift_dekkes_periode_id NUMBER(19),
    inntektsperiode_id           NUMBER(19) NOT NULL,
    skatteforhold_id             NUMBER(19) NOT NULL,
    CONSTRAINT pk_trygdeavgiftsperiode_grunnlag PRIMARY KEY (id),
    CONSTRAINT fk_tag_trygdeavgiftsperiode FOREIGN KEY (trygdeavgiftsperiode_id) REFERENCES trygdeavgiftsperiode (id) ON DELETE CASCADE,
    CONSTRAINT fk_tag_medlemskapsperiode FOREIGN KEY (medlemskapsperiode_id) REFERENCES medlemskapsperiode (id) ON DELETE SET NULL,
    CONSTRAINT fk_tag_lovvalgsperiode FOREIGN KEY (lovvalgsperiode_id) REFERENCES lovvalg_periode (id) ON DELETE SET NULL,
    CONSTRAINT fk_tag_helseutgift FOREIGN KEY (helseutgift_dekkes_periode_id) REFERENCES helseutgift_dekkes_periode (id) ON DELETE SET NULL,
    CONSTRAINT fk_tag_inntektsperiode FOREIGN KEY (inntektsperiode_id) REFERENCES inntektsperiode (id),
    CONSTRAINT fk_tag_skatteforhold FOREIGN KEY (skatteforhold_id) REFERENCES skatteforhold_til_norge (id)
);

-- Indeks for JPA lazy loading ytelse
CREATE INDEX idx_tag_trygdeavgiftsperiode ON trygdeavgiftsperiode_grunnlag (trygdeavgiftsperiode_id);

-- MELOSYS-7588: Migrer eksisterende grunnlag-data til ny tabell
INSERT INTO trygdeavgiftsperiode_grunnlag
    (trygdeavgiftsperiode_id, medlemskapsperiode_id, lovvalgsperiode_id,
     helseutgift_dekkes_periode_id, inntektsperiode_id, skatteforhold_id)
SELECT t.id,
       t.medlemskapsperiode_id,
       t.lovvalg_periode_id,
       t.helseutgift_dekkes_periode_id,
       t.inntektsperiode_id,
       t.skatteforhold_id
FROM trygdeavgiftsperiode t
WHERE t.inntektsperiode_id IS NOT NULL
  AND t.skatteforhold_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- MELOSYS-7969: Ny kolonne for beregningstype
-- ---------------------------------------------------------------------------
ALTER TABLE trygdeavgiftsperiode ADD beregningstype VARCHAR2(50);

UPDATE trygdeavgiftsperiode SET beregningstype = 'ORDINÆR';

-- Gjør trygdesats nullable (25%-regel og minstebeløp har ingen sats)
ALTER TABLE trygdeavgiftsperiode MODIFY trygdesats NULL;
