ALTER TABLE prosessinstans ADD prioritet VARCHAR2(10);

UPDATE prosessinstans SET prioritet = 'HØY' WHERE prosess_type IN (
    'IVERKSETT_VEDTAK_EOS',
    'IVERKSETT_VEDTAK_EOS_FORKORT_PERIODE',
    'IVERKSETT_VEDTAK_FTRL',
    'IVERKSETT_VEDTAK_IKKE_YRKESAKTIV',
    'IVERKSETT_VEDTAK_TRYGDEAVTALE',
    'JFR_ANDREGANG_NY_BEHANDLING',
    'JFR_ANDREGANG_REPLIKER_BEHANDLING',
    'JFR_KNYTT',
    'JFR_NY_SAK_BRUKER',
    'JFR_NY_SAK_VIRKSOMHET'
);

UPDATE prosessinstans SET prioritet = 'LAV' WHERE prosess_type IN (
    'OPPRETT_NY_BEHANDLING_AARSAVREGNING',
    'SATSENDRING',
    'SATSENDRING_TILBAKESTILL_NY_VURDERING'
);

UPDATE prosessinstans SET prioritet = 'NORMAL' WHERE prioritet IS NULL;

ALTER TABLE prosessinstans MODIFY prioritet VARCHAR2(10) NOT NULL;
