UPDATE FAGSAK f SET TEMA = 'UNNTAK' WHERE EXISTS
    (SELECT b.SAKSNUMMER FROM BEHANDLING b WHERE b.SAKSNUMMER = f.SAKSNUMMER AND b.BEH_TEMA IN
        ('ANMODNING_OM_UNNTAK_HOVEDREGEL',
        'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING',
        'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE',
        'BESLUTNING_LOVVALG_ANNET_LAND',
        'ØVRIGE_SED_UFM'));
UPDATE FAGSAK SET TEMA = 'MEDLEMSKAP_LOVVALG' WHERE TEMA IS NULL;

ALTER TABLE FAGSAK MODIFY TEMA NOT NULL;
