-- MELOSYS-8150: flytt TWFA-flagget (rammeavtale om fjernarbeid) fra prosessinstans.data til en durabel kolonne.
-- prosessinstans er en arbeidstabell som er ment aa slettes loepende (V161__prosessinstans_prioritet.sql),
-- og var frem til naa eneste lagringssted for saksbehandlerens avhuking. Presedens for kolonnen:
-- V7.6_07__saksbehandler_anmodet_om_unntak.sql la til anmodet_av paa samme tabell for tilsvarende formaal.
--
-- Tri-state bevares: NULL = ikke besvart (flagget kunne foerst settes 2026-02-22), 0 = nei, 1 = ja.
-- Bevisst UTEN DEFAULT, i motsetning til sendt_utland NUMBER(1) DEFAULT 0 i V4.4_03 paa samme tabell:
-- en DEFAULT 0 ville lest alle historiske rader som et registrert nei og oedelagt tri-staten som baade
-- uttrekket (WHERE = 1) og EessiService sin null-sjekk bygger paa. Presedens for nullbar form: V122.
--
-- Backfillen av historikken ligger bevisst i V171, ikke her: en nullbar kolonne uten default er ren
-- metadataendring paa Oracle 11g+ og tar millisekunder, mens backfillen skanner prosessinstans.data.
-- Splittet gjoer at en treg eller feilende backfill ikke kan holde oppstarten lenge nok til at
-- liveness-proben dreper podden foer kolonnen finnes -- feiler V171, virker koden, bare historikken mangler.
ALTER TABLE anmodningsperiode ADD er_fjernarbeid_twfa NUMBER(1);
