INSERT INTO BEHANDLING_TEMA (KODE, NAVN) VALUES ('ARBEID_TJENESTEPERSON_ELLER_FLY', 'Offentlig tjenesteperson/flyvende personell');
INSERT INTO BEHANDLING_TEMA (KODE, NAVN) VALUES ('ARBEID_KUN_NORGE', 'Arbeid kun i Norge');
