INSERT INTO BEHANDLINGSRESULTAT_TYPE(KODE, NAVN) VALUES ('MEDHOLD', 'Medhold på klage');
INSERT INTO BEHANDLINGSRESULTAT_TYPE(KODE, NAVN) VALUES ('KLAGEINNSTILLING', 'Klageinnstilling er oversendt til klageinstansen');
INSERT INTO BEHANDLINGSRESULTAT_TYPE(KODE, NAVN) VALUES ('AVVIST_KLAGE', 'Klage er avvist');
INSERT INTO BEHANDLINGSRESULTAT_TYPE(KODE, NAVN) VALUES ('OMGJORT', 'Vedtak er omgjort (fvl § 35)');
