INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('JFR_ANDREGANG_REPLIKER_BEHANDLING','Journalføring på eksisterende sak og repliker tidligere behandling');

UPDATE PROSESSINSTANS SET PROSESS_TYPE = 'JFR_ANDREGANG_REPLIKER_BEHANDLING' WHERE PROSESS_TYPE = 'JFR_NY_VURDERING';

DELETE PROSESS_TYPE WHERE KODE = 'JFR_NY_VURDERING';

INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('JFR_ANDREGANG_NY_BEHANDLING','Journalføring på eksisterende sak og opprett ny behandling');

INSERT INTO PROSESS_STEG (kode, navn) VALUES ('OPPRETT_NY_BEHANDLING', 'Oppretter ny behandling i Melosys');
