UPDATE BEHANDLING_TEMA
SET NAVN='MED: Henvendelse eller forespørsel'
WHERE KODE = 'ØVRIGE_SED_MED';

UPDATE BEHANDLING_TEMA
SET NAVN='UFM: Henvendelse eller forespørsel'
WHERE KODE = 'ØVRIGE_SED_UFM';
