UPDATE PROSESS_TYPE
SET KODE = 'OPPRETT_NY_SAK_EOS_FRA_OPPGAVE'
WHERE KODE = 'OPPRETT_NY_SAK_EOS';

UPDATE PROSESS_TYPE
SET KODE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE_FRA_OPPGAVE'
WHERE KODE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE';
