UPDATE PROSESS_TYPE
SET KODE = 'OPPRETT_NY_SAK_EOS_FRA_OPPGAVE'
WHERE KODE = 'OPPRETT_NY_SAK_EOS';

UPDATE PROSESS_TYPE
SET KODE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE_FRA_OPPGAVE'
WHERE KODE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE';

UPDATE PROSESSINSTANS
SET PROSESS_TYPE = 'OPPRETT_NY_SAK_EOS_FRA_OPPGAVE'
WHERE PROSESS_TYPE = 'OPPRETT_NY_SAK_EOS';

UPDATE PROSESSINSTANS
SET PROSESS_TYPE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE_FRA_OPPGAVE'
WHERE PROSESS_TYPE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE';

DELETE
FROM PROSESS_TYPE
WHERE KODE = 'OPPRETT_NY_SAK_EOS';

DELETE
FROM PROSESS_TYPE
WHERE KODE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE';

