INSERT INTO PROSESS_TYPE (KODE, NAVN)
VALUES ('OPPRETT_NY_SAK_EOS_FRA_OPPGAVE', 'Oppretter ny sak fra journalført dokument knyttet til oppgave for EU/EØS');
INSERT INTO PROSESS_TYPE (KODE, NAVN)
VALUES ('OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE_FRA_OPPGAVE', 'Oppretter ny sak fra journalført dokument knyttet til oppgave for FTRL og Trygdeavtale');

UPDATE PROSESSINSTANS
SET PROSESS_TYPE = 'OPPRETT_NY_SAK_EOS_FRA_OPPGAVE'
WHERE PROSESS_TYPE = 'OPPRETT_NY_SAK_EOS';

UPDATE PROSESSINSTANS
SET PROSESS_TYPE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE_FRA_OPPGAVE'
WHERE PROSESS_TYPE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE';

DELETE
FROM PROSESS_TYPE
WHERE KODE = 'OPPRETT_NY_SAK_EOS';

DELETE
FROM PROSESS_TYPE
WHERE KODE = 'OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE';

