INSERT INTO PROSESS_TYPE (KODE, NAVN)
VALUES ('OPPRETT_NY_BEHANDLING_FOR_SAK', 'Oppretter ny behandling og ny oppgave for eksisterende sak');
INSERT INTO PROSESS_TYPE (KODE, NAVN)
VALUES ('OPPRETT_REPLIKERT_BEHANDLING_FOR_SAK', 'Oppretter ny replikert behandling og ny oppgave for eksisterende sak');

UPDATE PROSESSINSTANS
SET PROSESS_TYPE = 'OPPRETT_NY_BEHANDLING_FOR_SAK'
WHERE PROSESS_TYPE = 'OPPRETT_BEHANDLING_FOR_SAK';

DELETE
FROM PROSESS_TYPE
WHERE KODE = 'OPPRETT_BEHANDLING_FOR_SAK';

