ALTER TABLE BEHANDLINGSGRUNNLAG RENAME TO MOTTATTEOPPLYSNINGER;

ALTER TABLE MOTTATTEOPPLYSNINGER DROP PRIMARY KEY;
ALTER TABLE MOTTATTEOPPLYSNINGER ADD CONSTRAINT PK_MOTTATTEOPPLYSNINGER PRIMARY KEY (id);

ALTER TABLE MOTTATTEOPPLYSNINGER DROP CONSTRAINT FK_BEHANDLINGSGRUNNLAG_BEHANDLING;
ALTER TABLE MOTTATTEOPPLYSNINGER ADD CONSTRAINT FK_MOTTATTEOPPLYSNINGER_BEHANDLING FOREIGN KEY (behandling_id) REFERENCES BEHANDLING;

ALTER INDEX IDX_EKSTERN_REFERANSE_ID_BEHANDLINGSGRUNNLAG RENAME TO IDX_EKSTERN_REFERANSE_ID_MOTTATTEOPPLYSNINGER;

DECLARE
    constraint_name_for_removal USER_CONSTRAINTS.CONSTRAINT_NAME%TYPE;
BEGIN
    SELECT CONSTRAINT_NAME INTO constraint_name_for_removal
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME='MOTTATTEOPPLYSNINGER'
    AND R_CONSTRAINT_NAME LIKE 'PK_BEHANDLINGSGRUNNNLAG_TYPE';

    EXECUTE IMMEDIATE 'ALTER TABLE MOTTATTEOPPLYSNINGER DROP CONSTRAINT ' || constraint_name_for_removal;
END;
/


ALTER TABLE BEHANDLINGSGRUNNLAG_TYPE RENAME TO MOTTATTEOPPLYSNINGER_TYPE;

ALTER TABLE MOTTATTEOPPLYSNINGER_TYPE DROP PRIMARY KEY;
ALTER TABLE MOTTATTEOPPLYSNINGER_TYPE ADD CONSTRAINT PK_MOTTATTEOPPLYSNINGER_TYPE PRIMARY KEY (kode);

ALTER TABLE MOTTATTEOPPLYSNINGER ADD CONSTRAINT FK_MOTTATTEOPPLYSNINGER_MOTTATTEOPPLYSNINGER_TYPE FOREIGN KEY (type) REFERENCES MOTTATTEOPPLYSNINGER_TYPE;



UPDATE PROSESS_STEG
SET NAVN = 'Oppretter mottatteopplysninger fra SED'
WHERE KODE = 'OPPRETT_SED_GRUNNLAG';




