DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_VALIDER_PERIODE'
                            OR KODE = 'REG_UNNTAK_VALIDER_MEDLEMSKAP'
                            OR KODE = 'REG_UNNTAK_VALIDER_YTELSER'
                            OR KODE = 'REG_UNNTAK_VALIDER_STATSBORGERSKAP';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('REG_UNNTAK_UNDER_AVKLARING', 'Unntaksperiode under avklaring');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('REG_UNNTAK_HENT_MEDLEMSKAP', 'Henter opplysninger om medlemskap');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('REG_UNNTAK_HENT_YTELSER', 'Henter opplysninger om ytelser');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('REG_UNNTAK_REGISTERKONTROLL', 'Validerer informasjon om en unntaksperiode');