ALTER TABLE BEHANDLINGSRESULTAT ADD UTFALL_REGISTRERING_UNNTAK VARCHAR2(40);

INSERT INTO PROSESS_STEG(kode, NAVN) VALUES ('REG_UNNTAK_PERIODE_IKKE_GODKJENT', 'Unntaksperiode ikke godkjent. Lagrer resultat og begrunnelser');

INSERT INTO BEHANDLINGSRESULTAT_TYPE(KODE, NAVN) VALUES ('REGISTRERT_UNNTAK', 'Om unntaksperioden har blitt godkjent for registrering');