CREATE TABLE BEHANDLINGSRES_BEGRUNNELSE(
    id                          NUMBER(19) GENERATED ALWAYS AS IDENTITY,
    beh_resultat_id             NUMBER(19) NOT NULL,
    kode                        VARCHAR2(99) NOT NULL,
    CONSTRAINT fk_beh_resultat  FOREIGN KEY (beh_resultat_id) REFERENCES BEHANDLINGSRESULTAT
);

ALTER TABLE BEHANDLINGSRESULTAT DROP COLUMN HENLEGGELSE_GRUNN;
ALTER TABLE BEHANDLINGSRESULTAT RENAME COLUMN HENLEGGELSE_FRITEKST TO BEGRUNNELSE_FRITEKST;
