INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('REG_UNNTAK_AVSLUTT_TIDLIGERE_PERIODE', 'Avslutter tidligere periode i Medl hvis SED er endring');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'REG_UNNTAK_AVSLUTT_TIDLIGERE_PERIODE' WHERE STEG = 'REG_UNNTAK_OPPDATER_BEHANDLING_OG_MEDL';
UPDATE PROSESSINSTANS SET STEG = 'REG_UNNTAK_AVSLUTT_TIDLIGERE_PERIODE' WHERE STEG = 'REG_UNNTAK_OPPDATER_BEHANDLING_OG_MEDL';
DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_OPPDATER_BEHANDLING_OG_MEDL';
