DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_FERDIGSTILL_JOURNALPOST';

INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES ('MOTTAK_SED', 'Journalføring og videre ruting for innkommende SED');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_FERDIGSTILL_JOURNALPOST', 'Journalføring av innkommende SED');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_RUTING', 'Bestemmer videre behandling for innkommende SED');
