INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('REGISTRERING_UNNTAK_NORSK_TRYGD', 'Registrering av unntak norsk trygd (A009,A010)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('UTL_MYND_UTPEKT_NORGE', 'Norge er utpekt (A003)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('UTL_MYND_UTPEKT_SEG_SELV', 'Utl. myndh. har utpekt seg selv (A003)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('ANMODNING_OM_UNNTAK_HOVEDREGEL', 'Behandling av en mottatt anmodning om unntak hovedregel (A001)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('ØVRIGE_SED', 'Behandling av alle øvrige SED');

UPDATE BEHANDLING SET BEH_TYPE = 'REGISTRERING_UNNTAK_NORSK_TRYGD' WHERE BEH_TYPE = 'UNNTAK_FRA_MEDLEMSKAP';

DELETE FROM BEHANDLING_TYPE WHERE KODE = 'UNNTAK_FRA_MEDLEMSKAP';
DELETE FROM BEHANDLING_TYPE WHERE KODE = 'NORGE_UTPEKT';
DELETE FROM BEHANDLING_TYPE WHERE KODE = 'PAASTAND_UTL';