INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('ANMODNING_OM_UNNTAK_MOTTAK_SVAR','Svar på mottatt anmodning om unntak');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_SVAR_SEND_SED', 'Send svar-sed');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_SVAR_OPPDATER_MEDL', 'Oppdater periode i Medl');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_SVAR_AVSLUTT_BEHANDLING', 'Avslutt behandling');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_SVAR_SAK_OG_BEHANDLING_AVSLUTTET', 'Oppdaterer status på sak i sob til avsluttet');
