INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('ANMODNING_OM_UNNTAK_SVAR','Mottar svar på anmodning om unntak');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_SVAR_OPPRETT_ANMODNINGSPERIODESVAR','Oppretter svar for en anmodningsperiode');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_SVAR_OPPDATER_BEHANDLING','Oppdater behandling');