INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('ANMODNING_OM_UNNTAK_MOTTAK','Mottar anmodning om unntak');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_OPPRETT_FAGSAK_OG_BEH','Opprett sak og behandling');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_OPPRETT_ANMODNINGSPERIODE', 'Opprett anmodningsperiode');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_OPPRETT_PERIODE_MEDL', 'Opprett periode under avklaring i Medl');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_SAK_OG_BEHANDLING_OPPRETTET', 'Oppdaterer status på sak i sob til opprettet');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_AVSLUTT_TIDLIGERE_PERIODE', 'Avslutter tidligere periode Medl hvis SED er endring');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_OPPRETT_SEDDOKUMENT', 'Oppretter sedinfo dokument');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_HENT_PERSON', 'Henter person tilknyttet SED');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_HENT_MEDLEMSKAP', 'Henter opplysninger om medlemskap');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_HENT_YTELSER', 'Henter opplysninger om ytelser');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_REGISTERKONTROLL', 'Validerer informasjon om en unntaksperiode');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('AOU_MOTTAK_OPPRETT_OPPGAVE', 'Opprett oppgave for manuell behandling');
