INSERT INTO ANMODNINGSPERIODE(BEH_RESULTAT_ID, FOM_DATO, TOM_DATO, LOVVALGSLAND, LOVVALG_BESTEMMELSE, TILLEGG_BESTEMMELSE, UNNTAK_FRA_LOVVALGSLAND, UNNTAK_FRA_BESTEMMELSE, MEDLPERIODE_ID)
    SELECT BEH_RESULTAT_ID, FOM_DATO, TOM_DATO, LOVVALGSLAND, LOVVALG_BESTEMMELSE, TILLEGG_BESTEMMELSE, UNNTAK_FRA_LOVVALGSLAND, UNNTAK_FRA_BESTEMMELSE, MEDLPERIODE_ID FROM LOVVALG_PERIODE
        WHERE UNNTAK_FRA_LOVVALGSLAND IS NOT NULL AND MEDLEMSKAPSTYPE = 'PLIKTIG';

DELETE FROM LOVVALG_PERIODE WHERE UNNTAK_FRA_LOVVALGSLAND IS NOT NULL AND MEDLEMSKAPSTYPE = 'PLIKTIG';

ALTER TABLE LOVVALG_PERIODE DROP (UNNTAK_FRA_LOVVALGSLAND, UNNTAK_FRA_BESTEMMELSE);