INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES ('MOTTAK_SED_JOURNALFØRING', 'Mottak av SED som kun skal journalføres');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_HENT_EESSI_MELDING', 'Henter saksopplysninger fra mottatt SED');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_OPPRETT_NY_BEHANDLING', 'Oppretter ny behandling for oppdatert SED');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_OPPRETT_SAK_OG_BEH', 'Opprett sak og behandling');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_OPPRETT_GSAK_SAK', 'Oppretter gsak sak for ny behandling');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SED_MOTTAK_OPPDATER_SAKSRELASJON', 'Oppdaterer saksrelasjon for ny gsak-sak');

DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_OPPRETT_SAK_OG_BEH';