INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING', 'Registrering av unntak fra norsk trygd – utstasjonerte (A009)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE', 'Registrering av unntak fra norsk trygd – øvrige (A010)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('VURDER_TRYGDETID', 'Behandling av forespørsel om trygdetid');

UPDATE BEHANDLING SET BEH_TYPE = 'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING' WHERE BEH_TYPE = 'REGISTRERING_UNNTAK_NORSK_TRYGD';
DELETE FROM BEHANDLING_TYPE WHERE KODE = 'REGISTRERING_UNNTAK_NORSK_TRYGD';

UPDATE LOVVALG_PERIODE SET LOVVALG_BESTEMMELSE = 'FO_883_2004_ART13_1B2' WHERE LOVVALG_BESTEMMELSE = 'FO_883_2004_ART13_1_B2';
UPDATE LOVVALG_PERIODE SET LOVVALG_BESTEMMELSE = 'FO_883_2004_ART13_1B3' WHERE LOVVALG_BESTEMMELSE = 'FO_883_2004_ART13_1_B3';
UPDATE LOVVALG_PERIODE SET LOVVALG_BESTEMMELSE = 'FO_883_2004_ART13_1B4' WHERE LOVVALG_BESTEMMELSE = 'FO_883_2004_ART13_1_B4';