DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_OPPRETT_SEDDOKUMENT';

INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES ('JFR_AOU_BREV', 'Journalføring av mottatt anmodning om unntak (brev)');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('JFR_AOU_BREV_OPPRETT_FAGSAK_OG_BEHANDLING', 'Opprett fagsak og behandling');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('JFR_AOU_BREV_OPPRETT_SEDDOKUMENT', 'Oppretter sed-dokument');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('JFR_AOU_BREV_OPPRETT_GSAK_SAK', 'Oppretter Sak i GSAK');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('JFR_AOU_BREV_FERDIGSTILL_JOURNALPOST', 'Journalføring av anmodning om unntak brev');
