INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AOU_MOTTAK_SVAR_OPPRETT_JOURNALPOST', 'Oppretter en journalpost av SEDen som skal sendes');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AOU_MOTTAK_SVAR_DISTRIBUER_JOURNALPOST', 'Distribuerer (sender) journalposten');
