UPDATE FAGSAK SET FAGSAK.REGISTRERT_AV = 'MELOSYS' WHERE FAGSAK.SAKSNUMMER IN (SELECT BEHANDLING.SAKSNUMMER FROM BEHANDLING WHERE BEH_TYPE IN ('REGISTRERING_UNNTAK_NORSK_TRYGD', 'VURDER_TRYGDETID', 'ØVRIGE_SED'));
UPDATE FAGSAK SET ENDRET_AV = 'MELOSYS' WHERE 1=1;

UPDATE BEHANDLING SET REGISTRERT_AV = 'MELOSYS' WHERE BEH_TYPE IN ('REGISTRERING_UNNTAK_NORSK_TRYGD', 'VURDER_TRYGDETID', 'ØVRIGE_SED');
UPDATE BEHANDLING SET ENDRET_AV = 'MELOSYS' WHERE 1=1;