UPDATE UTKAST_BREV
SET BREVBESTILLING_UTKAST = REPLACE(BREVBESTILLING_UTKAST, 'orgnrEtater', 'orgnrNorskMyndighet') ;

UPDATE UTKAST_BREV
SET BREVBESTILLING_UTKAST = REPLACE(BREVBESTILLING_UTKAST, 'ETAT', 'NORSK_MYNDIGHET') ;

UPDATE UTKAST_BREV
SET BREVBESTILLING_UTKAST = REPLACE(BREVBESTILLING_UTKAST, 'TRYGDEMYNDIGHET', 'UTENLANDSK_TRYGDEMYNDIGHET') ;
