INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_SØKNAD_ELLER_ANMODNING_ELLER_ATTEST', 'Oppretter ny Søknad eller AnmodningEllerAttest');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_SØKNAD_ELLER_ANMODNING_ELLER_ATTEST' WHERE STEG = 'OPPRETT_SØKNAD';
UPDATE PROSESSINSTANS SET SIST_FULLFORT_STEG = 'OPPRETT_SØKNAD_ELLER_ANMODNING_ELLER_ATTEST' WHERE SIST_FULLFORT_STEG = 'OPPRETT_SØKNAD';
DELETE FROM PROSESS_STEG WHERE KODE = 'OPPRETT_SØKNAD';
