INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_MOTTATTEOPPLYSNINGER', 'Oppretter mottatteopplysninger');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_MOTTATTEOPPLYSNINGER' WHERE STEG = 'OPPRETT_SØKNAD';
UPDATE PROSESSINSTANS SET SIST_FULLFORT_STEG = 'OPPRETT_MOTTATTEOPPLYSNINGER' WHERE SIST_FULLFORT_STEG = 'OPPRETT_SØKNAD';
DELETE FROM PROSESS_STEG WHERE KODE = 'OPPRETT_SØKNAD';
