INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AOU_MOTTAK_HENT_REGISTEROPPLYSNINGER', 'Henter saksopplysninger fra registre');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('REG_UNNTAK_HENT_REGISTEROPPLYSNINGER', 'Henter saksopplysninger fra registre');

DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_HENT_PERSON';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_HENT_MEDLEMSKAP';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_HENT_YTELSER';

DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_HENT_PERSON';
DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_HENT_MEDLEMSKAP';
DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_HENT_YTELSER';
