INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AOU_MOTTAK_HENT_REGISTEROPPLYSNINGER', 'Henter saksopplysninger fra registre');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('REG_UNNTAK_HENT_REGISTEROPPLYSNINGER', 'Henter saksopplysninger fra registre');

UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'AOU_MOTTAK_HENT_REGISTEROPPLYSNINGER' WHERE STEG IN ('AOU_MOTTAK_HENT_PERSON', 'AOU_MOTTAK_HENT_MEDLEMSKAP', 'AOU_MOTTAK_HENT_YTELSER');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'REG_UNNTAK_HENT_REGISTEROPPLYSNINGER' WHERE STEG IN ('REG_UNNTAK_HENT_PERSON', 'REG_UNNTAK_HENT_MEDLEMSKAP', 'REG_UNNTAK_HENT_YTELSER');

DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_HENT_PERSON';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_HENT_MEDLEMSKAP';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_MOTTAK_HENT_YTELSER';

DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_HENT_PERSON';
DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_HENT_MEDLEMSKAP';
DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_HENT_YTELSER';
