INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('BESLUTNING_LOVVALG_NORGE', 'Norge er utpekt (A003)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('BESLUTNING_LOVVALG_ANNET_LAND', 'Utl. myndh. har utpekt seg selv (A003)');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('SOEKNAD_ARBEID_FLERE_LAND', 'Søknad arbeid i flere land');
INSERT INTO BEHANDLING_TYPE(KODE, NAVN) VALUES('SOEKNAD_ARBEID_NORGE_BOSATT_ANNET_LAND', 'Søknad arbeid i Norge - bosatt i et annet land');

UPDATE BEHANDLING SET BEH_TYPE = 'BESLUTNING_LOVVALG_NORGE' WHERE BEH_TYPE = 'UTL_MYND_UTPEKT_NORGE';
UPDATE BEHANDLING SET BEH_TYPE = 'BESLUTNING_LOVVALG_ANNET_LAND' WHERE BEH_TYPE = 'UTL_MYND_UTPEKT_SEG_SELV';

DELETE FROM BEHANDLING_TYPE WHERE KODE = 'UTL_MYND_UTPEKT_NORGE';
DELETE FROM BEHANDLING_TYPE WHERE KODE = 'UTL_MYND_UTPEKT_SEG_SELV';

DELETE FROM avklartefakta WHERE referanse = 'YRKESAKTIVITET_ANTALL_LAND';
