INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_SAK_OG_BEHANDLING_OPPRETTET', 'Oppdaterer status på sak i sob til opprettet');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_AVSLUTT_TIDLIGERE_PERIODE', 'Avslutter tidligere periode hvis oppdatert SED');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_HENT_REGISTEROPPLYSNINGER', 'Innhenter registeropplysninger');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_OPPRETT_BEHANDLINGSGRUNNLAG', 'Oppretter behandlingsgrunnlag');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_REGISTERKONTROLL', 'Utfører registerkontroll');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_OPPRETT_OPPGAVE', 'Oppretter oppgave til manuell behandling');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('AFL_OPPDATER_MEDL', 'Setter status i MEDL');

INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('ARBEID_FLERE_ALND', 'Mottak av A003')