-- KONVERTER EKSISTERENDE RADER
UPDATE BEHANDLING b SET beh_tema = 'UTSENDT_SELVSTENDIG' WHERE beh_type = 'SOEKNAD' AND (select LOVVALG_BESTEMMELSE FROM LOVVALG_PERIODE l WHERE b.ID = l.BEH_RESULTAT_ID AND ROWNUM = 1) = 'FO_883_2004_ART12_2';
UPDATE BEHANDLING SET beh_tema = 'UTSENDT_ARBEIDSTAKER' WHERE beh_type = 'SOEKNAD' AND beh_tema IS NULL;

UPDATE BEHANDLING b SET beh_tema = 'UTSENDT_SELVSTENDIG' WHERE beh_type = 'NY_VURDERING' AND (select LOVVALG_BESTEMMELSE FROM LOVVALG_PERIODE l WHERE b.ID = l.BEH_RESULTAT_ID AND ROWNUM = 1) = 'FO_883_2004_ART12_2';
UPDATE BEHANDLING SET beh_tema = 'UTSENDT_ARBEIDSTAKER' WHERE beh_type = 'NY_VURDERING' AND beh_tema IS NULL;

UPDATE BEHANDLING b SET beh_tema = 'UTSENDT_SELVSTENDIG' WHERE beh_type = 'ENDRET_PERIODE' AND (select LOVVALG_BESTEMMELSE FROM LOVVALG_PERIODE l WHERE b.ID = l.BEH_RESULTAT_ID AND ROWNUM = 1) = 'FO_883_2004_ART12_2';
UPDATE BEHANDLING SET beh_tema = 'UTSENDT_ARBEIDSTAKER' WHERE beh_type = 'ENDRET_PERIODE' AND beh_tema IS NULL;

UPDATE BEHANDLING SET beh_tema = 'IKKE_YRKESAKTIV', beh_type = 'SOEKNAD' WHERE beh_type = 'SOEKNAD_IKKE_YRKESAKTIV';
UPDATE BEHANDLING SET beh_tema = 'ARBEID_FLERE_LAND', beh_type = 'SOEKNAD' WHERE beh_type = 'SOEKNAD_ARBEID_FLERE_LAND';
UPDATE BEHANDLING SET beh_tema = 'ARBEID_NORGE_BOSATT_ANNET_LAND', beh_type = 'SOEKNAD' WHERE beh_type = 'SOEKNAD_ARBEID_NORGE_BOSATT_ANNET_LAND';
UPDATE BEHANDLING SET beh_tema = 'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING', beh_type = 'SED' WHERE beh_type = 'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING';
UPDATE BEHANDLING SET beh_tema = 'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE', beh_type = 'SED' WHERE beh_type = 'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE';
UPDATE BEHANDLING SET beh_tema = 'BESLUTNING_LOVVALG_NORGE', beh_type = 'SED' WHERE beh_type = 'BESLUTNING_LOVVALG_NORGE';
UPDATE BEHANDLING SET beh_tema = 'BESLUTNING_LOVVALG_ANNET_LAND', beh_type = 'SED' WHERE beh_type = 'BESLUTNING_LOVVALG_ANNET_LAND';
UPDATE BEHANDLING SET beh_tema = 'ANMODNING_OM_UNNTAK_HOVEDREGEL', beh_type = 'SED' WHERE beh_type = 'ANMODNING_OM_UNNTAK_HOVEDREGEL';
UPDATE BEHANDLING SET beh_tema = 'ØVRIGE_SED', beh_type = 'SED' WHERE beh_type = 'ØVRIGE_SED';
UPDATE BEHANDLING SET beh_tema = 'TRYGDETID', beh_type = 'SED' WHERE beh_type = 'VURDER_TRYGDETID';

-- SLETT TYPER SOM ER FLYTTET TIL TEMA
DELETE FROM behandling_type WHERE kode = 'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING';
DELETE FROM behandling_type WHERE kode = 'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE';
DELETE FROM behandling_type WHERE kode = 'VURDER_TRYGDETID';
DELETE FROM behandling_type WHERE kode = 'SOEKNAD_IKKE_YRKESAKTIV';
DELETE FROM behandling_type WHERE kode = 'BESLUTNING_LOVVALG_NORGE';
DELETE FROM behandling_type WHERE kode = 'BESLUTNING_LOVVALG_ANNET_LAND';
DELETE FROM behandling_type WHERE kode = 'SOEKNAD_ARBEID_FLERE_LAND';
DELETE FROM behandling_type WHERE kode = 'SOEKNAD_ARBEID_NORGE_BOSATT_ANNET_LAND';
DELETE FROM behandling_type WHERE kode = 'ANMODNING_OM_UNNTAK_HOVEDREGEL';
DELETE FROM behandling_type WHERE kode = 'ØVRIGE_SED';

-- SETT CONTRAINT OG VALIDER beh_tema IKKE NULL
ALTER TABLE BEHANDLING MODIFY beh_tema NOT NULL;