ALTER TABLE PROSESSINSTANS_HENDELSER ADD (tmp_melding CLOB);
UPDATE PROSESSINSTANS_HENDELSER SET tmp_melding = melding;
ALTER TABLE PROSESSINSTANS_HENDELSER MODIFY melding NULL;
UPDATE PROSESSINSTANS_HENDELSER SET melding = null;
ALTER TABLE PROSESSINSTANS_HENDELSER MODIFY melding LONG;
ALTER TABLE PROSESSINSTANS_HENDELSER MODIFY melding CLOB;
UPDATE PROSESSINSTANS_HENDELSER SET melding = tmp_melding;
ALTER TABLE PROSESSINSTANS_HENDELSER MODIFY melding NOT NULL;
ALTER TABLE PROSESSINSTANS_HENDELSER DROP COLUMN tmp_melding;

-- Indexer må bygges på nytt
ALTER INDEX pk_pi_hendelser REBUILD;
