INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('JFR_HENT_REGISTER_OPPL', 'Hent registeropplysninger');

UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'JFR_HENT_REGISTER_OPPL'
WHERE STEG IN ('JFR_HENT_PERS_OPPL', 'HENT_ARBF_OPPL', 'HENT_INNT_OPPL', 'HENT_ORG_OPPL', 'HENT_MEDL_OPPL', 'HENT_SOB_SAKER');

UPDATE PROSESSINSTANS SET STEG = 'JFR_HENT_REGISTER_OPPL'
WHERE STEG IN ('JFR_HENT_PERS_OPPL', 'HENT_ARBF_OPPL', 'HENT_INNT_OPPL', 'HENT_ORG_OPPL', 'HENT_MEDL_OPPL', 'HENT_SOB_SAKER');

DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_HENT_PERS_OPPL', 'HENT_ARBF_OPPL', 'HENT_INNT_OPPL', 'HENT_ORG_OPPL', 'HENT_MEDL_OPPL', 'HENT_SOB_SAKER');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('VURDER_GJENBRUK_OPPGAVE', 'Vurder om eksisterende oppgave skal gjenbrukes');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'VURDER_GJENBRUK_OPPGAVE' WHERE STEG = 'OPPFRISK_SAKSOPPLYSNINGER';
UPDATE PROSESSINSTANS SET STEG = 'VURDER_GJENBRUK_OPPGAVE' WHERE STEG = 'OPPFRISK_SAKSOPPLYSNINGER';
DELETE FROM PROSESS_STEG WHERE KODE = 'VURDER_GJENBRUK_OPPGAVE';
