DELETE FROM VILKAARSRESULTAT v WHERE VILKAAR = 'FO_883_2004_INNGANGSVILKAAR';
INSERT INTO VILKAARSRESULTAT (BEH_RESULTAT_ID, VILKAAR, OPPFYLT, BEGRUNNELSE_FRITEKST, REGISTRERT_DATO, REGISTRERT_AV, ENDRET_DATO, ENDRET_AV)
SELECT r.BEHANDLING_ID, 'FO_883_2004_INNGANGSVILKAAR', 1, null, SYSDATE,'MELOSYS', SYSDATE, 'MELOSYS'
FROM FAGSAK f, BEHANDLING b, BEHANDLINGSRESULTAT r
WHERE f.FAGSAK_TYPE = 'EU_EOS'
  AND b.SAKSNUMMER = f.SAKSNUMMER
  AND b.BEH_TYPE = 'SOEKNAD'
  AND r.BEHANDLING_ID = b.ID;
