UPDATE FAGSAK F SET STATUS='AVSLUTTET' WHERE F.STATUS != 'AVSLUTTET' AND 'IKKE_GODKJENT' = (
          SELECT BR.UTFALL_REGISTRERING_UNNTAK FROM BEHANDLINGSRESULTAT BR JOIN BEHANDLING B on BR.BEHANDLING_ID = B.ID
            WHERE B.SAKSNUMMER=F.SAKSNUMMER ORDER BY ID DESC FETCH FIRST 1 ROW ONLY);