INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_OPPRETT_SAK_OG_BEHANDLING', 'Opprett sak og behandling fra søknad fra Altinn');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_OPPRETT_ARKIVSAK', 'Opprett arkivsak');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_OPPRETT_OG_FERDIGSTILL_JOURNALPOST', 'Opprett og journalfør søknad fra Altinn');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_HENT_REGISTEROPPLYSNINGER', 'Innhent registeropplysnigner');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_VURDER_INNGANGSVILKÅR', 'Vurder inngangsvilkår');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_OPPRETT_OPPGAVE', 'Opprett oppgave for saksbehandling');
INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('MSA_SEND_FORVALTNINGSMELDING', 'Send forvaltningsmelding');

UPDATE PROSESSINSTANS SET STEG = 'MSA_OPPRETT_SAK_OG_BEHANDLING' WHERE STEG = 'MSA_HENT_INNHOLD';
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'MSA_OPPRETT_SAK_OG_BEHANDLING' WHERE STEG = 'MSA_HENT_INNHOLD';

DELETE FROM PROSESS_STEG WHERE KODE = 'MSA_HENT_INNHOLD';
