DELETE
FROM SAKSOPPLYSNING_KILDE
WHERE KILDESYSTEM = 'SOB';

DELETE
FROM SAKSOPPLYSNING
WHERE OPPLYSNING_TYPE = 'SOB_SAK';

DELETE
FROM SAKSOPPLYSNING_KILDESYSTEM
WHERE KODE = 'SOB';

DELETE
FROM SAKSOPPLYSNING_TYPE
WHERE KODE = 'SOB_SAK';
