ALTER TABLE BEHANDLINGSRESULTAT
    ADD NY_VURDERING_BAKGRUNN VARCHAR2(4000);

UPDATE
    BEHANDLINGSRESULTAT behandlingsresultat
SET
    behandlingsresultat.NY_VURDERING_BAKGRUNN = (SELECT vedtak_metadata.NY_VURDERING_BAKGRUNN FROM VEDTAK_METADATA vedtak_metadata WHERE vedtak_metadata.behandlingsresultat_id = behandlingsresultat.BEHANDLING_ID);

ALTER TABLE VEDTAK_METADATA
    DROP COLUMN NY_VURDERING_BAKGRUNN CASCADE CONSTRAINTS;
