ALTER TABLE BEHANDLINGSGRUNNLAG_TYPE MODIFY (KODE VARCHAR(100));
INSERT INTO BEHANDLINGSGRUNNLAG_TYPE(KODE, BESKRIVELSE) VALUES ('SØKNAD_A1_YRKESAKTIVE_EØS', 'Søknad om A1 for yrkesaktive innen EØS/Sveits');
INSERT INTO BEHANDLINGSGRUNNLAG_TYPE(KODE, BESKRIVELSE) VALUES ('SØKNAD_A1_UTSENDTE_ARBEIDSTAKERE_EØS', 'Søknad om A1 for utsendte arbeidstakere innen EØS/Sveits');
INSERT INTO BEHANDLINGSGRUNNLAG_TYPE(KODE, BESKRIVELSE) VALUES ('SØKNAD_FOLKETRYGDEN','Søknad om medlemskap i folketrygden');

UPDATE BEHANDLINGSGRUNNLAG_TYPE SET KODE = 'SØKNAD_A1_YRKESAKTIVE_EØS' WHERE KODE = 'SØKNAD';

DELETE FROM BEHANDLINGSGRUNNLAG_TYPE WHERE KODE IN ('GENERELT', 'SØKNAD');