UPDATE SAKSOPPLYSNING S SET S.DOKUMENT_XML = deleteXML(S.DOKUMENT_XML, '/sedDokument/erElektronisk')
    WHERE S.OPPLYSNING_TYPE = 'SEDOPPL';
UPDATE SAKSOPPLYSNING S SET S.INTERN_XML = deleteXML(S.INTERN_XML, '/sedDokument/erElektronisk')
    WHERE S.OPPLYSNING_TYPE = 'SEDOPPL';
