ALTER TABLE PROSESSINSTANS ADD (STATUS VARCHAR2(20));
UPDATE PROSESSINSTANS SET STATUS = 'FERDIG' WHERE STEG = 'FERDIG';
UPDATE PROSESSINSTANS SET STATUS = 'FEILET' WHERE STEG = 'FEILET_MASKINELT';
UPDATE PROSESSINSTANS SET STATUS = 'KLAR' WHERE STATUS IS NULL;
ALTER TABLE PROSESSINSTANS MODIFY (STATUS NOT NULL);
CREATE INDEX idx_prosessinstans_status ON PROSESSINSTANS(status);

ALTER TABLE PROSESSINSTANS RENAME COLUMN steg TO sist_fullfort_steg;
ALTER TABLE PROSESSINSTANS MODIFY (STEG NULL);
ALTER TABLE PROSESSINSTANS DROP COLUMN antall_retry;
ALTER TABLE PROSESSINSTANS DROP COLUMN sover_til;

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPDATER_OG_FERDIGSTILL_JOURNALPOST', 'Oppdaterer og ferdigstiller journalposten i Joark');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPDATER_OG_FERDIGSTILL_JOURNALPOST' WHERE STEG IN ('JFR_OPPDATER_JOURNALPOST', 'JFR_FERDIGSTILL_JOURNALPOST');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_OPPDATER_JOURNALPOST', 'JFR_FERDIGSTILL_JOURNALPOST');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('HENT_REGISTEROPPLYSNINGER', 'Henter registeropplysninger');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'HENT_REGISTEROPPLYSNINGER' WHERE STEG = 'JFR_HENT_REGISTER_OPPL';
DELETE FROM PROSESS_STEG WHERE KODE = 'HENT_REGISTEROPPLYSNINGER';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_OPPGAVE', 'Oppretter behandlingsoppgave');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_OPPGAVE' WHERE STEG = 'GSAK_OPPRETT_OPPGAVE';
DELETE FROM PROSESS_STEG WHERE KODE = 'GSAK_OPPRETT_OPPGAVE';

DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG IN ('JFR_VALIDERING', 'JFR_VURDER_JOURNALFOERINGSTYPE', 'JFR_AKTØR_ID');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_VALIDERING', 'JFR_VURDER_JOURNALFOERINGSTYPE', 'JFR_AKTØR_ID');