ALTER TABLE PROSESSINSTANS ADD (STATUS VARCHAR2(20));
UPDATE PROSESSINSTANS SET STATUS = 'FERDIG' WHERE STEG = 'FERDIG';
UPDATE PROSESSINSTANS SET STATUS = 'FEILET' WHERE STEG = 'FEILET_MASKINELT';
UPDATE PROSESSINSTANS SET STATUS = 'KLAR' WHERE STATUS IS NULL;
ALTER TABLE PROSESSINSTANS MODIFY (STATUS NOT NULL);
CREATE INDEX idx_prosessinstans_status ON PROSESSINSTANS(status);

ALTER TABLE PROSESSINSTANS RENAME COLUMN steg TO sist_fullfort_steg;
ALTER TABLE PROSESSINSTANS MODIFY (STEG NULL);
ALTER TABLE PROSESSINSTANS DROP COLUMN antall_retry;
ALTER TABLE PROSESSINSTANS DROP COLUMN sover_til;

UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'HS_SEND_BREV' WHERE STEG IN ('HS_HENLEGG_SAK', 'HS_OPPDATER_RESULTAT');
DELETE FROM PROSESS_STEG WHERE KODE IN ('HS_HENLEGG_SAK', 'HS_OPPDATER_RESULTAT');

UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'VS_AVKLAR_MYNDIGHET' WHERE STEG = 'VS_OPPDATER_RESULTAT';
DELETE FROM PROSESS_STEG WHERE KODE = 'VS_OPPDATER_RESULTAT';

DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG IN ('AOU_VALIDERING', 'AOU_OPPDATER_RESULTAT');
DELETE FROM PROSESS_STEG WHERE KODE IN ('AOU_VALIDERING', 'AOU_OPPDATER_RESULTAT');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPDATER_OG_FERDIGSTILL_JOURNALPOST', 'Oppdaterer og ferdigstiller journalposten i Joark');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPDATER_OG_FERDIGSTILL_JOURNALPOST' WHERE STEG IN ('JFR_OPPDATER_JOURNALPOST', 'JFR_FERDIGSTILL_JOURNALPOST');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_OPPDATER_JOURNALPOST', 'JFR_FERDIGSTILL_JOURNALPOST');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('HENT_REGISTEROPPLYSNINGER', 'Henter registeropplysninger');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'HENT_REGISTEROPPLYSNINGER' WHERE STEG IN ('JFR_HENT_REGISTER_OPPL',
                                                                                      'AOU_MOTTAK_HENT_REGISTEROPPLYSNINGER',
                                                                                      'AFL_HENT_REGISTEROPPLYSNINGER',
                                                                                      'REG_UNNTAK_HENT_REGISTEROPPLYSNINGER',
                                                                                     'SED_GENERELL_SAK_HENT_PERSON');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_HENT_REGISTER_OPPL', 'AOU_MOTTAK_HENT_REGISTEROPPLYSNINGER',
                                        'AFL_HENT_REGISTEROPPLYSNINGER', 'REG_UNNTAK_HENT_REGISTEROPPLYSNINGER',
                                        'SED_GENERELL_SAK_HENT_PERSON');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_OPPGAVE', 'Oppretter behandlingsoppgave');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_OPPGAVE' WHERE STEG IN ('GSAK_OPPRETT_OPPGAVE', 'AOU_MOTTAK_OPPRETT_OPPGAVE', 'AFL_OPPRETT_OPPGAVE', 'REG_UNNTAK_OPPRETT_OPPGAVE', 'SED_GENERELL_SAK_OPPRETT_OPPGAVE');
DELETE FROM PROSESS_STEG WHERE KODE  IN ('GSAK_OPPRETT_OPPGAVE', 'AOU_MOTTAK_OPPRETT_OPPGAVE', 'AFL_OPPRETT_OPPGAVE', 'REG_UNNTAK_OPPRETT_OPPGAVE', 'SED_GENERELL_SAK_OPPRETT_OPPGAVE');

DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG IN ('JFR_VALIDERING', 'JFR_VURDER_JOURNALFOERINGSTYPE', 'JFR_AKTØR_ID', 'VURDER_GJENBRUK_OPPGAVE');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_VALIDERING', 'JFR_VURDER_JOURNALFOERINGSTYPE', 'JFR_AKTØR_ID', 'VURDER_GJENBRUK_OPPGAVE');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_ARKIVSAK', 'Oppretter arkivsak');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_ARKIVSAK' WHERE STEG = 'JFR_OPPRETT_GSAK_SAK';
DELETE FROM PROSESS_STEG WHERE KODE = 'JFR_OPPRETT_GSAK_SAK';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('VURDER_INNGANGSVILKÅR', 'Vurderer inngangsvilkår');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'VURDER_INNGANGSVILKÅR' WHERE STEG IN ('JFR_VURDER_INNGANGSVILKÅR', 'AFL_VURDER_INNGANGSVILKÅR');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_VURDER_INNGANGSVILKÅR', 'AFL_VURDER_INNGANGSVILKÅR');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES('SEND_ORIENTERING_ANMODNING_UNNTAK', 'Send orienteringsbrev til bruker ved anmodning om unntak');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'SEND_ORIENTERING_ANMODNING_UNNTAK' WHERE STEG = 'AOU_SEND_BREV';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_SEND_BREV';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('SEND_ANMODNING_OM_UNNTAK', 'Sender anmodning om unntak til utenlandsk trygdemyndighet');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'SEND_ANMODNING_OM_UNNTAK' WHERE STEG = 'AOU_SEND_SED';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_SEND_SED';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPDATER_OPPGAVE_ANMODNING_UNNTAK_SENDT', 'Oppdaterer oppgave med frist og beskrivelse');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPDATER_OPPGAVE_ANMODNING_UNNTAK_SENDT' WHERE STEG = 'AOU_OPPDATER_OPPGAVE';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_OPPDATER_OPPGAVE';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPDATER_MEDL_ANMODNING_UNNTAK', 'Setter periode til under avklaring i MEDL ved anmodning om unntak');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPDATER_MEDL_ANMODNING_UNNTAK' WHERE STEG = 'AOU_OPPDATER_MEDL';
DELETE FROM PROSESS_STEG WHERE KODE = 'AOU_OPPDATER_MEDL';

DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG IN ('IV_VALIDERING');
DELETE FROM PROSESS_STEG WHERE KODE IN ('IV_VALIDERING');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('AVKLAR_MYNDIGHET','Avklaring av utenlandsk trygdemyndighet');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'AVKLAR_MYNDIGHET' WHERE STEG IN ('VS_AVKLAR_MYNDIGHET', 'AOU_AVKLAR_MYNDIGHET', 'IV_AVKLAR_MYNDIGHET');
DELETE FROM PROSESS_STEG WHERE KODE IN ('VS_AVKLAR_MYNDIGHET', 'AOU_AVKLAR_MYNDIGHET', 'IV_AVKLAR_MYNDIGHET');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('AVKLAR_ARBEIDSGIVER','Avklaring av norsk arbeidsgiver');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'AVKLAR_ARBEIDSGIVER' WHERE STEG = 'IV_AVKLAR_ARBEIDSGIVER';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_AVKLAR_ARBEIDSGIVER';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPDATER_MEDL_VED_VEDTAK', 'Oppdaterer MEDL ved vedtak');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPDATER_MEDL_VED_VEDTAK' WHERE STEG = 'IV_OPPDATER_MEDL';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_OPPDATER_MEDL';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('SEND_VEDTAKSBREV_INNLAND', 'Sender vedtaksbrev innland');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'SEND_VEDTAKSBREV_INNLAND' WHERE STEG = 'IV_SEND_BREV';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_SEND_BREV';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('SEND_VEDTAK_UTLAND', 'Sender vedtaket til utland');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'SEND_VEDTAK_UTLAND' WHERE STEG = 'IV_SEND_SED';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_SEND_SED';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('DISTRIBUER_JOURNALPOST_UTLAND', 'Distribuerer (sender) en journalpost til utlanlandsk myndighet');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'DISTRIBUER_JOURNALPOST_UTLAND' WHERE STEG IN ('UL_DISTRIBUER_JOURNALPOST', 'VS_DISTRIBUER_JOURNALPOST');
DELETE FROM PROSESS_STEG WHERE KODE IN ('UL_DISTRIBUER_JOURNALPOST', 'VS_DISTRIBUER_JOURNALPOST');

DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG = 'IV_OPPDATER_RESULTAT';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_OPPDATER_RESULTAT';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_AVGIFTSOPPGAVE', 'Oppretter en vurderingsoppgave for innregistrering i avgiftsystemet');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_AVGIFTSOPPGAVE' WHERE STEG = 'IV_OPPRETT_AVGIFTSOPPGAVE';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_OPPRETT_AVGIFTSOPPGAVE';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('AVSLUTT_BEHANDLING', 'Avslutt fagsak og aktiv behandling');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'AVSLUTT_BEHANDLING' WHERE STEG = 'IV_AVSLUTT_BEHANDLING';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_AVSLUTT_BEHANDLING';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('SOB_BEHANDLING_AVSLUTTET', 'Oppdaterer SOB (Sak Og Behandling) om avsluttet behandling');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'SOB_BEHANDLING_AVSLUTTET' WHERE STEG = 'IV_STATUS_BEH_AVSL';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_STATUS_BEH_AVSL';

INSERT INTO PROSESS_STEG VALUES ('HENT_MOTTAKERINSTITUSJON_FORKORTET_PERIODE', 'Henter mottakerinstitusjon fra tidligere sendt BUC ved forkortet periode');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'HENT_MOTTAKERINSTITUSJON_FORKORTET_PERIODE' WHERE STEG = 'IV_FORKORT_PERIODE';
DELETE FROM PROSESS_STEG WHERE KODE = 'IV_FORKORT_PERIODE';

DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG = 'SED_MOTTAK_OPPRETT_JFR_OPPG';
DELETE FROM PROSESS_STEG WHERE KODE = 'SED_MOTTAK_OPPRETT_JFR_OPPG';

UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_ARKIVSAK' WHERE STEG = 'SED_MOTTAK_OPPRETT_SAK';
DELETE FROM PROSESS_STEG WHERE KODE = 'SED_MOTTAK_OPPRETT_SAK';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPDATER_SAKSRELASJON', 'Oppdaterer saksrelasjon mellom melosys-sak og rina-sak');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPDATER_SAKSRELASJON' WHERE STEG IN ('JFR_OPPDATER_SAKSRELASJON', 'SED_MOTTAK_OPPDATER_SAKSRELASJON');
DELETE FROM PROSESS_STEG WHERE KODE IN ('JFR_OPPDATER_SAKSRELASJON', 'SED_MOTTAK_OPPDATER_SAKSRELASJON');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('SOB_BEHANDLING_OPPRETTET', 'Oppdaterer SOB (Sak Og Behandling) om opprettet behandling');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'SOB_BEHANDLING_OPPRETTET' WHERE STEG IN ('STATUS_BEH_OPPR',
                                                                                     'REG_UNNTAK_SAK_OG_BEHANDLING_OPPRETTET',
                                                                                     'AFL_SAK_OG_BEHANDLING_OPPRETTET',
                                                                                     'AOU_MOTTAK_SAK_OG_BEHANDLING_OPPRETTET');
DELETE FROM PROSESS_STEG WHERE KODE IN ('STATUS_BEH_OPPR', 'REG_UNNTAK_SAK_OG_BEHANDLING_OPPRETTET',
                                        'AFL_SAK_OG_BEHANDLING_OPPRETTET', 'AOU_MOTTAK_SAK_OG_BEHANDLING_OPPRETTET');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_SEDDOKUMENT', 'Oppretter saksopplysning fra SED');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_SEDDOKUMENT' WHERE STEG IN ('REG_UNNTAK_OPPRETT_SEDDOKUMENT');
DELETE FROM PROSESS_STEG WHERE KODE IN ('REG_UNNTAK_OPPRETT_SEDDOKUMENT');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('AVSLUTT_TIDLIGERE_MEDL_PERIODE', 'Avslutter tidligere periode i Medl');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'AVSLUTT_TIDLIGERE_MEDL_PERIODE'
WHERE STEG IN ('REG_UNNTAK_AVSLUTT_TIDLIGERE_PERIODE', 'AFL_AVSLUTT_TIDLIGERE_PERIODE',
               'AOU_MOTTAK_AVSLUTT_TIDLIGERE_PERIODE');
DELETE FROM PROSESS_STEG WHERE KODE IN ('REG_UNNTAK_AVSLUTT_TIDLIGERE_PERIODE', 'AFL_AVSLUTT_TIDLIGERE_PERIODE',
                                        'AOU_MOTTAK_AVSLUTT_TIDLIGERE_PERIODE');

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('REGISTERKONTROLL', 'Utfører registerkontroll for en behandling');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'REGISTERKONTROLL' WHERE STEG IN ('AFL_REGISTERKONTROLL',
                                                                             'REG_UNNTAK_REGISTERKONTROLL',
                                                                            'AOU_MOTTAK_REGISTERKONTROLL');
DELETE FROM PROSESS_STEG WHERE KODE IN ('AFL_REGISTERKONTROLL', 'REG_UNNTAK_REGISTERKONTROLL', 'AOU_MOTTAK_REGISTERKONTROLL');

INSERT INTO PROSESS_STEG(kode, navn) VALUES ('BESTEM_BEHANDLINGMÅTE_SED', 'Bestemmer videre behandlingsmåte for en mottatt SED etter registerkontroll');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'BESTEM_BEHANDLINGMÅTE_SED' WHERE STEG = 'REG_UNNTAK_BESTEM_BEHANDLINGSMAATE';
DELETE FROM PROSESS_STEG WHERE KODE = 'REG_UNNTAK_BESTEM_BEHANDLINGSMAATE';

INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_SED_GRUNNLAG', 'Oppretter behandlingsgrunnlag fra SED');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_SED_GRUNNLAG' WHERE STEG = 'AFL_OPPRETT_BEHANDLINGSGRUNNLAG';
DELETE FROM PROSESS_STEG WHERE KODE = 'AFL_OPPRETT_BEHANDLINGSGRUNNLAG';