DELETE FROM PROSESSINSTANS_HENDELSER WHERE STEG='MANGELBREV';
DELETE FROM PROSESSINSTANS WHERE SIST_FULLFORT_STEG='MANGELBREV';
DELETE FROM PROSESSINSTANS WHERE PROSESS_TYPE='MANGELBREV';
DELETE FROM PROSESS_STEG WHERE KODE='MANGELBREV';
DELETE FROM PROSESS_TYPE WHERE KODE='MANGELBREV';