INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('IVERKSETT_VEDTAK_EOS','Iverksett vedtak EOS');
INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('IVERKSETT_VEDTAK_EOS_FORKORT_PERIODE','Iverksett nytt vedtak etter lovvalgsperioden har blitt forkortet');
INSERT INTO PROSESS_STEG (kode, navn) VALUES ('LAGRE_MEDLEMSKAPSPERIODE_MEDL', 'Lagrer en medlemskapsperiode (Folketrygden) i MEDL som endelig');
INSERT INTO PROSESS_STEG (kode, navn) VALUES ('PUBLISER_VEDTAK', 'Publiserer vedtak på Kafka');


UPDATE PROSESSINSTANS SET TYPE = 'IVERKSETT_VEDTAK_EOS' WHERE TYPE = 'IVERKSETT_VEDTAK';
UPDATE PROSESSINSTANS SET TYPE = 'IVERKSETT_VEDTAK_EOS_FORKORT_PERIODE WHERE' TYPE = 'IVERKSETT_VEDTAK_FORKORT_PERIODE';

DELETE PROSESS_TYPE WHERE KODE = 'IVERKSETT_VEDTAK_FORKORT_PERIODE';
