INSERT INTO SAKSOPPLYSNING_TYPE(KODE, NAVN) VALUES ('PDL_PERSOPL', 'Personopplysning fra PDL');
INSERT INTO SAKSOPPLYSNING_TYPE(KODE, NAVN) VALUES ('PDL_PERS_SAKS', 'Personopplysning fra PDL til saksbehandler');
