update BEHANDLING b
set BEHANDLINGSFRIST = b.REGISTRERT_DATO + 30
where b.BEH_TEMA IN ('UTSENDT_ARBEIDSTAKER', 'UTSENDT_SELVSTENDIG', 'ARBEID_FLERE_LAND', 'ARBEID_ETT_LAND_ØVRIG', 'IKKE_YRKESAKTIV', 'ARBEID_I_UTLANDET', 'ARBEID_NORGE_BOSATT_ANNET_LAND', 'TRYGDEAVTALE_UK')
  AND b.BEHANDLINGSFRIST IS null AND b.REGISTRERT_DATO IS NOT null;

update BEHANDLING b
set BEHANDLINGSFRIST = b.REGISTRERT_DATO + 14 -- 2 uker
where b.BEH_TEMA IN ('REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING', 'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE')
  AND b.BEHANDLINGSFRIST IS null AND b.REGISTRERT_DATO IS NOT null;

update BEHANDLING b
set BEHANDLINGSFRIST = b.REGISTRERT_DATO + 28 -- 4 uker
where b.BEH_TEMA IN ('BESLUTNING_LOVVALG_NORGE', 'BESLUTNING_LOVVALG_ANNET_LAND')
  AND b.BEHANDLINGSFRIST IS null AND b.REGISTRERT_DATO IS NOT null;

update BEHANDLING b
set BEHANDLINGSFRIST = b.REGISTRERT_DATO + 56 -- 8 uker
where b.BEH_TEMA IN ('ANMODNING_OM_UNNTAK_HOVEDREGEL', 'ØVRIGE_SED_UFM', 'ØVRIGE_SED_MED', 'TRYGDETID')
  AND b.BEHANDLINGSFRIST IS null AND b.REGISTRERT_DATO IS NOT null;
