UPDATE VEDTAK_METADATA
SET REVURDER_BEGRUNNELSE = 'FEIL_I_BEHANDLING'
WHERE REVURDER_BEGRUNNELSE IN ('SAKSBEHANDLER_OPPDAGET_FEIL', 'HENVENDELSE_OM_OPPDAGET_FEIL', 'HENVENDELSE_OM_FEIL_BRUKER');

ALTER TABLE VEDTAK_METADATA RENAME COLUMN REVURDER_BEGRUNNELSE TO NY_VURDERING_BAKGRUNN;
