insert into VEDTAK_METADATA(BEHANDLINGSRESULTAT_ID, VEDTAK_DATO, VEDTAK_KLAGEFRIST, VEDTAK_TYPE, REVURDER_BEGRUNNELSE, REGISTRERT_DATO, ENDRET_DATO, REGISTRERT_AV, ENDRET_AV)
SELECT B.ID, BRES.ENDRET_DATO, BRES.ENDRET_DATO + 42, 'ENDRINGSVEDTAK', NULL, BRES.ENDRET_DATO, BRES.ENDRET_DATO, BRES.ENDRET_AV, BRES.ENDRET_AV
FROM BEHANDLING B JOIN BEHANDLINGSRESULTAT BRES ON B.ID = BRES.BEHANDLING_ID
WHERE B.BEH_TYPE='ENDRET_PERIODE'
  AND B.STATUS='AVSLUTTET'
  AND BRES.RESULTAT_TYPE='FASTSATT_LOVVALGSLAND'
  AND B.ID NOT IN (SELECT BEHANDLINGSRESULTAT_ID FROM VEDTAK_METADATA);
