INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('IVERKSETT_VEDTAK_TRYGDEAVTALE','Iverksett vedtak Trygdeavtale');
INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('IVERKSETT_VEDTAK_FTRL','Iverksett vedtak Folketrygdloven');

UPDATE PROSESSINSTANS SET PROSESS_TYPE = 'IVERKSETT_VEDTAK_FTRL' WHERE PROSESS_TYPE = 'IVERKSETT_VEDTAK';

DELETE PROSESS_TYPE WHERE KODE = 'IVERKSETT_VEDTAK';
