INSERT INTO PROSESS_TYPE (KODE, NAVN) VALUES ('OPPRETT_NY_SAK_EOS', 'Oppretter ny sak (fra journalført dokument) for EU/EØS');
INSERT INTO PROSESS_TYPE (KODE, NAVN) VALUES ('OPPRETT_NY_SAK_FTRL_TRYGDEAVTALE', 'Oppretter ny sak (fra journalført dokument) for FTRL og Trygdeavtale');

UPDATE PROSESSINSTANS SET PROSESS_TYPE = 'OPPRETT_NY_SAK_EOS' WHERE PROSESS_TYPE = 'OPPRETT_NY_SAK';

DELETE FROM PROSESS_TYPE WHERE KODE = 'OPPRETT_NY_SAK';
