INSERT INTO BEHANDLING_TEMA(KODE, NAVN) VALUES ('YRKESAKTIV', 'Yrkesaktiv');

UPDATE BEHANDLING SET beh_tema = 'YRKESAKTIV' WHERE beh_tema = 'TRYGDEAVTALE_UK';

DELETE FROM BEHANDLING_TEMA WHERE KODE = 'TRYGDEAVTALE_UK';
