INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('OPPRETT_SAK_OG_BEH', 'Oppretter ny sak og behandling i Melosys');
INSERT INTO PROSESS_STEG (KODE, NAVN) VALUES ('OPPRETT_SØKNAD', 'Oppretter ny søknad i Melosys');

UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_SAK_OG_BEH' WHERE STEG = 'JFR_OPPRETT_SAK_OG_BEH';
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_SØKNAD' WHERE STEG = 'JFR_OPPRETT_SØKNAD';

UPDATE PROSESSINSTANS SET SIST_FULLFORTE_STEG = 'OPPRETT_SAK_OG_BEH' WHERE SIST_FULLFORTE_STEG = 'JFR_OPPRETT_SAK_OG_BEH';
UPDATE PROSESSINSTANS SET SIST_FULLFORTE_STEG = 'OPPRETT_SØKNAD' WHERE SIST_FULLFORTE_STEG = 'JFR_OPPRETT_SØKNAD';

DELETE FROM PROSESS_STEG WHERE KODE = 'JFR_OPPRETT_SAK_OG_BEH';
DELETE FROM PROSESS_STEG WHERE KODE = 'JFR_OPPRETT_SØKNAD';
