INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('JFR_NY_SAK_BRUKER','Journalføring med ny sak og søknad for bruker');
INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('JFR_NY_SAK_VIRKSOMHET','Journalføring med ny sak for virksomhet');

UPDATE PROSESSINSTANS SET PROSESS_TYPE = 'JFR_NY_SAK_BRUKER' WHERE PROSESS_TYPE = 'JFR_NY_SAK';
UPDATE PROSESSINSTANS_HENDELSER SET TYPE = 'JFR_NY_SAK_BRUKER' WHERE TYPE = 'JFR_NY_SAK';

DELETE PROSESS_TYPE WHERE KODE = 'JFR_NY_SAK';
