INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES('JFR_NY_VURDERING','Journalføring på eksisterende sak (ny vurdering) oppretter en ny behandling');

UPDATE PROSESSINSTANS SET PROSESS_TYPE = 'JFR_NY_VURDERING' WHERE PROSESS_TYPE = 'JFR_NY_BEHANDLING';
UPDATE PROSESSINSTANS_HENDELSER SET TYPE = 'JFR_NY_VURDERING' WHERE TYPE = 'JFR_NY_BEHANDLING';

DELETE PROSESS_TYPE WHERE KODE = 'JFR_NY_BEHANDLING';
