UPDATE BEHANDLING_DVH
SET RESULTAT_TYPE = 'FERDIGBEHANDLET'
WHERE (BEH_TEMA = 'TRYGDETID' OR BEH_TEMA = 'FORESPØRSEL_TRYGDEMYNDIGHET' OR BEH_TEMA = 'IKKE_YRKESAKTIV')
  AND status = 'AVSLUTTET' AND RESULTAT_TYPE = 'IKKE_FASTSATT';

UPDATE BEHANDLING_DVH
SET RESULTAT_TYPE = 'REGISTRERT_UNNTAK'
WHERE (BEH_TEMA = 'ANMODNING_OM_UNNTAK_HOVEDREGEL' OR BEH_TEMA = 'BESLUTNING_LOVVALG_ANNET_LAND' OR BEH_TEMA = 'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING' OR BEH_TEMA = 'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE')
  AND status = 'AVSLUTTET' AND RESULTAT_TYPE = 'IKKE_FASTSATT'
  AND BEHANDLING_ID IN (
    SELECT BEHANDLING_ID
    FROM BEHANDLINGSRESULTAT
    WHERE (UTFALL_REGISTRERING_UNNTAK = 'GODKJENT' OR UTFALL_REGISTRERING_UNNTAK = 'DELVIS_GODKJENT')
);

UPDATE BEHANDLING_DVH
SET RESULTAT_TYPE = 'REGISTRERT_UNNTAK'
WHERE (BEH_TEMA = 'ANMODNING_OM_UNNTAK_HOVEDREGEL' OR BEH_TEMA = 'BESLUTNING_LOVVALG_ANNET_LAND' OR BEH_TEMA = 'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING' OR BEH_TEMA = 'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE')
  AND status = 'AVSLUTTET' AND RESULTAT_TYPE = 'IKKE_FASTSATT'
  AND BEHANDLING_ID IN (
    SELECT BEHANDLING_ID
    FROM BEHANDLINGSRESULTAT
    WHERE (UTFALL_REGISTRERING_UNNTAK = 'IKKE_GODKJENT' OR UTFALL_REGISTRERING_UNNTAK is null)
);
