-- V70__oppdatere_trygdedekning.sql erstattet deler av kode og ikke eksakt kode, denne patchen retter opp

UPDATE MOTTATTEOPPLYSNINGER
SET DATA = REPLACE(
            DATA,
            'HELSE_OG_FTRL_2_9_FØRSTE_LEDD_B_PENSJON',
            'FTRL_2_9_FØRSTE_LEDD_C_HELSE_PENSJON'
    )
WHERE JSON_VALUE(DATA, '$.trygdedekning') = 'HELSE_OG_FTRL_2_9_FØRSTE_LEDD_B_PENSJON';

UPDATE MOTTATTEOPPLYSNINGER
SET DATA = REPLACE(
            DATA,
            'HELSE_OG_FTRL_2_9_FØRSTE_LEDD_B_PENSJON_MED_SYKE_OG_FORELDREPENGER',
            'FTRL_2_9_FØRSTE_LEDD_C_ANDRE_LEDD_HELSE_PENSJON_SYKE_FORELDREPENGER'
    )
WHERE JSON_VALUE(DATA, '$.trygdedekning') = 'HELSE_OG_FTRL_2_9_FØRSTE_LEDD_B_PENSJON_MED_SYKE_OG_FORELDREPENGER';

UPDATE MOTTATTEOPPLYSNINGER
SET DATA = REPLACE(
            DATA,
            'FTRL_2_9_FØRSTE_LEDD_A_HELSE_MED_SYKE_OG_FORELDREPENGER',
            'FTRL_2_9_FØRSTE_LEDD_A_ANDRE_LEDD_HELSE_SYKE_FORELDREPENGER'
    )
WHERE JSON_VALUE(DATA, '$.trygdedekning') = 'FTRL_2_9_FØRSTE_LEDD_A_HELSE_MED_SYKE_OG_FORELDREPENGER';
