INSERT INTO MOTTATTEOPPLYSNINGER_TYPE(KODE, BESKRIVELSE) VALUES ('SØKNAD_YRKESAKTIVE_NORGE_ELLER_UTENFOR_EØS','Søknadsopplysninger om yrkesaktive utenfor EØS eller i Norge');

UPDATE MOTTATTEOPPLYSNINGER SET TYPE = 'SØKNAD_YRKESAKTIVE_NORGE_ELLER_UTENFOR_EØS' WHERE TYPE = 'SØKNAD_FOLKETRYGDEN' OR TYPE = 'SØKNAD_TRYGDEAVTALE';

DELETE FROM MOTTATTEOPPLYSNINGER_TYPE WHERE KODE = 'SØKNAD_FOLKETRYGDEN' OR KODE = 'SØKNAD_TRYGDEAVTALE';
