ALTER TABLE BEHANDLINGSAARSAK_TYPE MODIFY kode VARCHAR2(40);
ALTER TABLE BEHANDLINGSAARSAK MODIFY aarsak_type VARCHAR2(40);

INSERT INTO BEHANDLINGSAARSAK_TYPE(kode, beskrivelse) VALUES ('MELDING_OM_MANGLENDE_INNBETALING', 'Melding om manglende innbetaling');

DELETE FROM PROSESS_STEG WHERE KODE = 'LAGRE_FAKTURASERIE_REFERANSE';

