INSERT INTO BEHANDLINGSAARSAK_TYPE(kode, beskrivelse) VALUES ('MELDING_OM_MANGLENDE_INNBETALING', 'Melding om manglende innbetaling');

DELETE FROM PROSESS_STEG WHERE KODE = 'LAGRE_FAKTURASERIE_REFERANSE';

