INSERT INTO PROSESS_STEG(KODE, NAVN) VALUES ('OPPRETT_FAKTURASERIE', 'Oppretter fakturaserie i faktureringskomponenten');
UPDATE PROSESSINSTANS_HENDELSER SET STEG = 'OPPRETT_FAKTURASERIE' WHERE STEG = 'OPPRETT_BETALINGSPLAN';
UPDATE PROSESSINSTANS SET SIST_FULLFORT_STEG = 'OPPRETT_FAKTURASERIE' WHERE SIST_FULLFORT_STEG = 'OPPRETT_BETALINGSPLAN';
DELETE FROM PROSESS_STEG WHERE KODE = 'OPPRETT_BETALINGSPLAN';
