UPDATE BEHANDLINGSRESULTAT
SET BEHANDLINGSMAATE='MANUELT',
    ENDRET_DATO=CURRENT_TIMESTAMP,
    ENDRET_AV='MELOSYS'
WHERE BEHANDLINGSMAATE = 'UDEFINERT';

DELETE
FROM BEHANDLINGSMAATE
WHERE KODE = 'UDEFINERT';

UPDATE BEHANDLINGSRESULTAT
SET BEHANDLINGSMAATE='MANUELT',
    ENDRET_DATO=CURRENT_TIMESTAMP,
    ENDRET_AV='MELOSYS'
WHERE BEHANDLING_ID
          IN (SELECT b.ID
              FROM BEHANDLING b
                       JOIN BEHANDLINGSRESULTAT br ON b.ID = br.BEHANDLING_ID
              WHERE br.BEHANDLINGSMAATE = 'AUTOMATISERT'
                AND b.BEH_TYPE = 'NY_VURDERING');
