INSERT INTO PROSESS_TYPE(KODE, NAVN) VALUES ('OPPDATER_FAKTURAMOTTAKER', 'Oppdaterer fakturamottaker på eventuell faktura til sak');

UPDATE PROSESSINSTANS SET PROSESS_TYPE = 'OPPDATER_FAKTURAMOTTAKER' WHERE PROSESS_TYPE = 'OPPDATER_FAKTURA';

DELETE PROSESS_TYPE WHERE KODE = 'OPPDATER_FAKTURA';
