// @no-cookie-jar
// @no-log
POST https://melosys-api.intern.nav.no/admin/prosessinstanser/feilede/restart
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
X-MELOSYS-ADMIN-APIKEY: {{melosys-admin-api-key}}

{}

###
