package no.nav.melosys.domain.brev

enum class BrevkopiRegel {
    BRUKER_FÅR_KOPI,
    ARBEIDSGIVER_FÅR_KOPI,
    UTENLANDSK_TRYGDEMYNDIGHET_FÅR_KOPI,
    UTENLANDSK_TRYGDEMYNDIGHET_FÅR_KOPI_HVIS_IKKE_ART_8_2
}
