package no.nav.melosys.domain.brev;

public enum BrevkopiRegel {
    BRUKER_FÅR_KOPI,
    BRUKER_FÅR_KOPI_HVIS_FULLMEKTIG_FINNES,
    ARBEIDSGIVER_FÅR_KOPI_HVIS_IKKE_SELVBETALENDE_BRUKER,
    SKATT_FÅR_KOPI_HVIS_AVGIFTSPLIKTIG_INNTEKT
}
