package db.local.testdata;

import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Objects;

import no.nav.melosys.domain.SaksopplysningKildesystem;
import no.nav.melosys.domain.SaksopplysningType;
import no.nav.melosys.domain.dokument.XsltConfig;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.OraclePreparedStatement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.core.io.support.ResourcePatternResolver;

@SuppressWarnings("unused")
public class V1_1_05__SAKSOPPLYSNING_data extends BaseJavaMigration {
    private static final Logger log = LoggerFactory.getLogger(V1_1_05__SAKSOPPLYSNING_data.class);

    private static final String DB_FLYWAY_MIGRATION_TESTDATA_XML = "db/local/testdata/xml";

    private final ResourcePatternResolver resourcePatternResolver;
    private int currentRowNum = 0;

    public V1_1_05__SAKSOPPLYSNING_data() {
        this.resourcePatternResolver = new PathMatchingResourcePatternResolver();
    }

    @Override
    public void migrate(Context context) throws Exception {
        Resource resource = new DefaultResourceLoader().getResource("classpath:" + DB_FLYWAY_MIGRATION_TESTDATA_XML);
        if (!resource.exists()) {
            throw new IOException("Filområdet for Flyway-migreringstestdata script finnes ikke : " + DB_FLYWAY_MIGRATION_TESTDATA_XML);
        }

        Resource[] resources = resourcePatternResolver.getResources("classpath*:" + "**/" + DB_FLYWAY_MIGRATION_TESTDATA_XML + "/*");

        Connection conn = context.getConnection();
        if (conn.isWrapperFor(OracleConnection.class)) {
            conn = conn.unwrap(OracleConnection.class);
        }
        for (Resource dir : resources) {
            batchInsertForDirectory(conn, dir);
        }
        // Setter neste primærnøkkel satt med identity til å ha verdien max(TRANSACTION_ID) + 1 (for å unngå feil med entydighetsskranken)
        try (Statement alterTable = conn.createStatement()) {
            alterTable.execute("ALTER TABLE SAKSOPPLYSNING MODIFY id generated BY DEFAULT as identity (START WITH LIMIT VALUE)");
        }
    }

    private void batchInsertForDirectory(Connection conn, Resource dir) throws IOException {
        String dirName;
        if (dir.getURL().getProtocol().equals("jar")) {
            String[] segments = dir.getURL().getPath().split("/");
            dirName = segments[segments.length-1];
        } else {
            dirName = dir.getFilename();
        }

        switch (Objects.requireNonNull(dirName)) {
            case XsltConfig.AAREG_MAPPE:
                generateBatch(conn, dir, SaksopplysningType.ARBFORH, "3.0", SaksopplysningKildesystem.AAREG);
                return;
            case XsltConfig.EREG_MAPPE:
                generateBatch(conn, dir, SaksopplysningType.ORG, "4.0", SaksopplysningKildesystem.EREG);
                return;
            case XsltConfig.INNTK_MAPPE:
                generateBatch(conn, dir, SaksopplysningType.INNTK, "3.2", SaksopplysningKildesystem.INNTK);
                return;
            case XsltConfig.TPS_MAPPE:
                generateBatch(conn, dir, SaksopplysningType.PERSOPL, "3.0", SaksopplysningKildesystem.TPS);
                return;
            case "pershist":
                generateBatch(conn, dir, SaksopplysningType.PERSHIST, "3.4", SaksopplysningKildesystem.TPS);
                return;
            case XsltConfig.MEDL_MAPPE:
                generateBatch(conn, dir, SaksopplysningType.MEDL, "2.0", SaksopplysningKildesystem.MEDL);
                return;
            default:
                throw new IllegalStateException("Unknown xml data directory: " + dir.getFilename());
        }
    }

    private void generateBatch(Connection connection, Resource dir, SaksopplysningType opplysning_type, String versjon, SaksopplysningKildesystem kilde) throws IOException {
        log.info("Creating batch inserts for directory: {}", dir.getDescription());
        Resource[] resources = resourcePatternResolver.getResources(dir.getURL() + "*.xml");
        for (int i = 0; i < resources.length; i++) {
            insertXML(resources[i], connection, opplysning_type, versjon, kilde, i);
        }
    }

    private String[] getBehandlingsIder(String filename) {
        String[] nameParts = filename.split("-");
        if (nameParts.length != 2) {throw new UnsupportedOperationException("Filnavn må følge {behandlingsId}-beskrivendenavn.xml"); }
        return nameParts[0].split("_");
    }

    private void insertXML(Resource file, Connection conn, SaksopplysningType opplysning_type, String versjon, SaksopplysningKildesystem kilde, int i) {
        for (String behandlingsidText : getBehandlingsIder(file.getFilename())) {
            int behandlingsid = Integer.parseInt(behandlingsidText);

            String query = "INSERT INTO SAKSOPPLYSNING (ID, BEHANDLING_ID, OPPLYSNING_TYPE, VERSJON, KILDE, REGISTRERT_DATO, ENDRET_DATO, DOKUMENT_XML) VALUES (?, ?, ?, ?, ?, ?, ?, XMLType(?)) ";
            try (OraclePreparedStatement ps = (OraclePreparedStatement) conn.prepareStatement(query)) {
                ps.setInt(1, currentRowNum++);
                ps.setInt(2, behandlingsid);
                ps.setString(3, opplysning_type.getKode());
                ps.setString(4, versjon);
                ps.setString(5, kilde.getKode());
                Timestamp x = Timestamp.valueOf(LocalDateTime.now());
                ps.setTimestamp(6, x);
                ps.setTimestamp(7, x);
                ps.setCharacterStream(8, new InputStreamReader(file.getInputStream()), file.contentLength());
                if (ps.executeUpdate() == 1) {
                    log.info("Successfully inserted {} {}, behandlingsid: {}", i, file.getFilename(), behandlingsid);
                }
            } catch (Exception e) {
                log.error("", e);
            }
        }
    }
}