UPDATE FAGSAK_DVH f
SET TEMA = 'UNNTAK'
WHERE EXISTS
          (SELECT b.SAKSNUMMER
           FROM BEHANDLING b
           WHERE b.SAKSNUMMER = f.FAGSAK_ID
             AND b.BEH_TEMA IN
                 ('ANMODNING_OM_UNNTAK_HOVEDREGEL',
                  'REGISTRERING_UNNTAK_NORSK_TRYGD_UTSTASJONERING',
                  'REGISTRERING_UNNTAK_NORSK_TRYGD_ØVRIGE',
                  'BESLUTNING_LOVVALG_ANNET_LAND',
                  'ØVRIGE_SED_UFM'));

UPDATE FAGSAK_DVH f
SET TEMA = 'UNNTAK'
WHERE FAGSAK_TYPE = 'TRYGDEAVTALE'
  AND EXISTS
    (SELECT b.SAKSNUMMER
     FROM BEHANDLING b
     WHERE b.SAKSNUMMER = f.FAGSAK_ID
       AND b.BEH_TEMA = 'ANMODNING_OM_UNNTAK_HOVEDREGEL'
    );

UPDATE FAGSAK_DVH
SET TEMA = 'MEDLEMSKAP_LOVVALG'
WHERE TEMA IS NULL;

ALTER TABLE FAGSAK_DVH
    MODIFY TEMA NOT NULL;
