-- Et par SEDer ble mottatt når toggle var skrudd av etter migrering ble kjørt
UPDATE BEHANDLING_DVH
SET BEH_TEMA = 'FORESPØRSEL_TRYGDEMYNDIGHET'
WHERE BEH_TEMA in ('ØVRIGE_SED_MED', 'ØVRIGE_SED_UFM', 'ØVRIGE_SED');

UPDATE BEHANDLING_DVH
SET BEH_TEMA = 'ARBEID_TJENESTEPERSON_ELLER_FLY'
WHERE BEH_TEMA = 'ARBEID_ETT_LAND_ØVRIG';

UPDATE BEHANDLING_DVH
SET BEH_TEMA = 'YRKESAKTIV'
WHERE BEH_TEMA = 'ARBEID_I_UTLANDET';

UPDATE BEHANDLING_DVH
SET BEH_TYPE = 'FØRSTEGANG'
WHERE BEH_TYPE in ('SED', 'SOEKNAD');

UPDATE BEHANDLING_DVH
SET BEH_TYPE = 'HENVENDELSE'
WHERE BEH_TEMA = 'FORESPØRSEL_TRYGDEMYNDIGHET';
