// @no-cookie-jar
// @no-log
PUT https://{{melosys-api-url}}/admin/fagsaker/{{saksnummer}}}}/henlegg-bortfalt
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
X-MELOSYS-ADMIN-APIKEY: {{melosys-admin-api-key}}

{}

###
